import type { DocPage } from "@/docs/types";

/**
 * Menambahkan Storage
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "add-storage",
  title: "Menambahkan Storage",
  group: "Panduan Admin",
  order: 60,
  icon: "server",
  description: "Mengelola Multi R2 Storage Manager - menambah akun R2 baru, menguji koneksi, menyinkronkan pemakaian, mengedit, menonaktifkan, dan menghapus storage.",
  updated: "2026-09-19",
  body: [
    "Halaman **Admin → Storage** (`/admin/storage`) adalah pusat kendali *Multi R2 Storage Manager*. Di sinilah",
    "beberapa akun Cloudflare R2 digabungkan menjadi satu pool.",
    "",
    "## Ringkasan pool",
    "",
    "Bagian atas halaman menampilkan agregat seluruh storage:",
    "",
    "- **Total kapasitas** - jumlah `Storage Limit` semua storage.",
    "- **Terpakai / Sisa** - akumulasi pemakaian dan ruang kosong.",
    "- **Node aktif** - berapa storage berstatus `active`.",
    "- **Ruang terbesar** - free space terbesar, yaitu kandidat utama untuk upload berikutnya.",
    "",
    "Setiap kartu storage menampilkan bar pemakaian (`8 GB / 10 GB`), status, waktu pemeriksaan terakhir, dan",
    "aksi cepat.",
    "",
    "## Menambah storage baru",
    "",
    "1. Klik **Tambah Storage**.",
    "2. Isi form:",
    "",
    "| Field | Wajib | Keterangan |",
    "| --- | --- | --- |",
    "| **Storage Name** | Ya | Label internal, misal `R2 Server 1`. Harus unik. |",
    "| **Account ID** | Ya | 32 karakter heksadesimal dari dashboard Cloudflare. |",
    "| **Bucket Name** | Ya | Nama bucket R2 (huruf kecil/angka/strip/titik). |",
    "| **Access Key ID** | Ya | Dari API token S3 R2. |",
    "| **Secret Access Key** | Ya | Hanya muncul sekali saat token dibuat. |",
    "| **Storage Limit** | Ya | Kuota yang Anda tetapkan untuk storage ini, misal `10 GB`. Angka ini yang dipakai algoritma seleksi. |",
    "| **Priority** | Tidak | Angka kecil = lebih dulu dipilih bila free space seri. Default 100. |",
    "| **Endpoint** | Tidak | Kosongkan agar otomatis memakai `https://<account-id>.r2.cloudflarestorage.com`. |",
    "| **Region** | Tidak | Default `auto` (nilai yang benar untuk R2). |",
    '| **Notes** | Tidak | Catatan bebas, misal "akun email kedua". |',
    "| **Uji koneksi sebelum menyimpan** | - | Default aktif. Bila gagal, storage tetap dibuat tetapi ditandai `error` beserta alasannya. |",
    "",
    "3. Klik **Simpan Storage**.",
    "",
    '> [!NOTE] Kenapa "Storage Limit" diisi manual?',
    "> Cloudflare tidak menyediakan API untuk membaca sisa kuota per akun. Karena itu Anda menetapkan batas",
    "> (misalnya 10 GB untuk kuota gratis) dan aplikasi menghitung pemakaian dari metadata file yang diupload,",
    "> lalu bisa disinkronkan dengan isi bucket sebenarnya kapan saja.",
    "",
    "## Test koneksi",
    "",
    "Tombol **Test** menjalankan empat pemeriksaan berurutan dan menampilkan hasil tiap langkah beserta durasinya:",
    "",
    "| Langkah | Memeriksa | Gagal biasanya berarti |",
    "| --- | --- | --- |",
    "| Akses bucket (`HeadBucket`) | Endpoint + Account ID + nama bucket benar | Account ID salah, bucket tidak ada, atau token tidak mencakup bucket ini |",
    "| Baca daftar objek (`ListObjectsV2`) | Izin baca | Permission token bukan *Object Read & Write* |",
    "| Tulis objek uji (`PutObject`) | Izin tulis | Permission token kurang, atau bucket terkunci kebijakan |",
    "| Hapus objek uji (`DeleteObject`) | Izin hapus + kebersihan | Permission kurang |",
    "",
    "Pesan error sudah diterjemahkan ke penyebab yang paling mungkin, misalnya:",
    "",
    "- `AccessDenied` → Access Key ID / Secret Access Key salah, atau token tidak mencakup bucket.",
    "- `SignatureDoesNotMatch` → Secret Access Key salah ketik.",
    "- `NoSuchBucket` → nama bucket atau Account ID keliru.",
    "",
    "## Sinkronisasi pemakaian",
    "",
    "Angka **Terpakai** secara normal dihitung dari metadata file yang diupload lewat aplikasi (cepat dan murah).",
    "Bila Anda pernah menaruh file langsung ke bucket lewat dashboard Cloudflare, angka itu bisa berbeda.",
    "",
    "Klik **Sync** pada kartu storage untuk menghitung ulang dari bucket sebenarnya. Sistem melakukan paginasi",
    "`ListObjectsV2` (sampai 100 halaman = 100.000 objek) dan menjumlahkan seluruh ukuran, termasuk sisa",
    "multipart upload yang belum dibersihkan.",
    "",
    "> [!TIP] Rutinkan sync",
    "> Jalankan **Sync** setelah membersihkan objek manual, atau sebulan sekali untuk memastikan angka kuota",
    "> tetap akurat sehingga pemilihan storage otomatis tidak salah hitung.",
    "",
    "## Mengedit storage",
    "",
    "Klik **Edit** untuk mengubah nama, limit, priority, endpoint, catatan, atau status.",
    "",
    "- Field **Secret Access Key** dibiarkan kosong bila tidak ingin diganti - nilai lama tetap dipakai.",
    "- Setelah mengubah kredensial, aktifkan **Uji koneksi** agar status langsung diperbarui.",
    "- Mengubah **Account ID** atau **Bucket** tidak memindahkan file yang sudah ada; gunakan fitur",
    "  **Pindahkan** di File Manager untuk itu.",
    "",
    "## Menonaktifkan & menghapus",
    "",
    "- **Nonaktifkan** (`status = disabled`): storage tidak dipilih untuk upload baru dan file di dalamnya tidak",
    "  bisa diunduh sementara, tetapi metadata serta objek tetap utuh. Cocok saat token sedang dirotasi.",
    "- **Hapus**: menghapus entri storage dari pool.",
    "  - Bila masih ada file di dalamnya, aplikasi menolak dan menampilkan jumlah file tersebut.",
    "  - Pilih **Paksa hapus** hanya bila Anda memang ingin metadata file tetap ada namun tidak dapat diunduh",
    "    (statusnya menjadi *Storage dihapus*).",
    "  - Menghapus storage **tidak** menghapus objek di bucket R2. Objek tetap ada sampai Anda menghapusnya dari",
    "    dashboard Cloudflare.",
    "",
    "## Algoritma pemilihan storage otomatis",
    "",
    "Saat sebuah file diupload, sistem memilih storage dengan aturan berikut:",
    "",
    "1. Hanya storage berstatus **active** dengan kredensial lengkap yang dipertimbangkan.",
    "2. Storage harus punya **sisa kapasitas >= ukuran file**.",
    "3. Dari kandidat yang lolos, dipilih yang **free space-nya paling besar**.",
    "4. Bila seri, `priority` terkecil menang, lalu urutan nama (deterministik).",
    "5. Bila admin memilih storage tertentu secara manual di form upload, pilihan itu dipakai selama kapasitasnya",
    "   cukup.",
    "",
    "Contoh dari spesifikasi:",
    "",
    "```text",
    "File yang diupload : 6 GB",
    "",
    "R2 1 : sisa 2 GB   -> tidak cukup       (ditolak)",
    "R2 2 : sisa 8 GB   -> cukup, terbesar   (DIPILIH)",
    "R2 3 : sisa 0 GB   -> penuh             (ditolak)",
    "",
    "Keputusan: upload ke R2 2, alasan dicatat di sesi upload dan ditampilkan di UI.",
    "```",
    "",
    "Bila tidak ada storage yang memenuhi syarat, API mengembalikan `507 no_storage_available` beserta daftar",
    "kandidat dan alasan masing-masing - panel upload menampilkannya apa adanya agar jelas apa yang harus",
    "dibereskan.",
    "",
    "## Keamanan kredensial",
    "",
    "- **Secret Access Key** dienkripsi **AES-256-GCM** dengan `CREDENTIAL_ENCRYPTION_KEY` sebelum disimpan ke",
    "  database. Nilai terenkripsi berawalan `enc:v1:`.",
    "- **Access Key ID** disimpan apa adanya (bukan rahasia), tetapi **selalu** dikirim ke browser dalam bentuk",
    "  tersamar, misalnya `8f2a****c31d`.",
    "- Tidak ada endpoint API mana pun yang mengembalikan Secret Access Key, termasuk saat mengedit storage.",
    "- Kredensial hanya didekripsi di memori server, tepat sebelum menandatangani request S3.",
    "",
    "Detail lengkap ada di [Security Guide](/docs/security).",
    "",
    "## Selanjutnya",
    "",
    "- [Upload Guide](/docs/upload-guide) - mengunggah file pertama ke pool.",
    "- [File Management](/docs/file-management) - memindahkan file antar storage.",
  ].join("\n"),
};
