import type { DocPage } from "@/docs/types";

/**
 * Database Setup (D1 atau KV)
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "database-setup",
  title: "Database Setup (D1 atau KV)",
  group: "Cloudflare",
  order: 30,
  icon: "database",
  description: "Memilih antara Cloudflare D1 dan KV, membuat database/namespace dari dashboard, membuat API token Cloudflare, dan menginisialisasi tabel tanpa terminal.",
  updated: "2026-09-19",
  body: [
    "Katsu R2 Manager menyimpan **metadata** (daftar storage, daftar file, sesi upload, dan state rate limit)",
    "di Cloudflare. Isi file tetap di R2; database hanya menyimpan catatan kecil yang membuat semuanya bisa",
    "dicari, diurutkan, dan dilacak lokasinya.",
    "",
    "Dua driver didukung:",
    "",
    "| Driver | Cocok untuk | Kekuatan | Catatan |",
    "| --- | --- | --- | --- |",
    "| **D1** (disarankan) | Semua pemakaian serius | SQL, indeks, transaksi per statement, query cepat, bisa diekspor | Perlu inisialisasi tabel sekali |",
    "| **KV** | Library kecil / uji coba | Setup paling sederhana, tanpa skema | Konsistensi *eventual*, indeks dibaca-tulis ulang, disarankan di bawah beberapa ratus file |",
    "",
    "Keduanya diakses melalui **HTTP API Cloudflare**, bukan binding, sehingga kode yang sama jalan di Vercel",
    "maupun Cloudflare Workers/Pages. Yang dibutuhkan hanya tiga environment variable:",
    "`CLOUDFLARE_ACCOUNT_ID`, `CLOUDFLARE_API_TOKEN`, dan `DATABASE_ID` (D1) atau `KV_NAMESPACE_ID` (KV).",
    "",
    "## Bagian A - Cloudflare D1 (disarankan)",
    "",
    "### A1. Buat database",
    "",
    "1. Buka [dash.cloudflare.com](https://dash.cloudflare.com).",
    "2. Sidebar → **Storage & Databases** → **D1**.",
    "3. Klik **Create database**.",
    "4. Nama: `katsu-r2-manager`. Lokasi: biarkan default (atau pilih **Jurisdiction** bila diperlukan).",
    "5. Klik **Create**.",
    "6. Setelah jadi, buka database tersebut dan salin **Database ID** (UUID) - inilah nilai `DATABASE_ID`.",
    "",
    "### A2. Buat tabel",
    "",
    "Ada dua cara, keduanya tanpa terminal:",
    "",
    "**Cara 1 - lewat aplikasi (paling mudah)**",
    "",
    "1. Deploy aplikasi dan isi environment variables (lihat [Deployment](/docs/deployment)).",
    "2. Login ke `/admin`, buka **Settings** → bagian **Database**.",
    "3. Klik **Initialize database**. Aplikasi menjalankan seluruh DDL melalui D1 HTTP API dan melaporkan",
    "   hasilnya.",
    "",
    "**Cara 2 - lewat D1 Console di dashboard**",
    "",
    "1. Buka database Anda di dashboard → tab **Console**.",
    "2. Salin seluruh isi file [`database/schema.sql`](https://github.com/Recva-by-katsu/My-srtg/blob/main/database/schema.sql)",
    "   dari repository.",
    "3. Tempel di editor SQL, lalu klik **Execute**.",
    "",
    "Skema yang dibuat:",
    "",
    "```sql",
    "storages        -- akun R2 dalam pool (kredensial terenkripsi)",
    "files           -- metadata file + download_id publik + lokasi object",
    "upload_sessions -- sesi multipart (mendukung resume upload)",
    "app_state       -- state pendek: rate limit, job pemindahan file",
    "meta            -- versi skema",
    "```",
    "",
    "### A3. Buat API token Cloudflare (untuk D1 HTTP API)",
    "",
    "1. Klik avatar Anda (pojok kanan atas) → **My Profile** → **API Tokens**.",
    "2. Klik **Create Token** → pilih **Custom token** (paling bawah).",
    "3. Isi:",
    "   - **Token name**: `katsu-r2-manager-db`",
    "   - **Permissions**:",
    "     - `Account` → `D1` → **Edit**",
    "     - `Account` → `Account Settings` → **Read**",
    "     - (bila memakai KV) `Account` → `Workers KV Storage` → **Edit**",
    "   - **Account Resources**: **Include** → akun Anda",
    "   - **Zone Resources**: biarkan **All zones** / kosong (tidak dibutuhkan)",
    "   - **TTL**: pilih tanggal mulai & berakhir sesuai kebijakan Anda",
    "4. Klik **Continue to summary** → **Create Token**.",
    "5. Salin token - inilah nilai `CLOUDFLARE_API_TOKEN`. Token hanya ditampilkan sekali.",
    "",
    "> [!WARNING] Jangan pakai Global API Key",
    "> Global API Key memberi akses penuh ke seluruh akun. Selalu buat token khusus dengan izin minimal",
    "> seperti di atas.",
    "",
    "### A4. Set environment variables",
    "",
    "Di dashboard hosting (Cloudflare Workers/Pages → **Settings** → **Variables and Secrets**, atau Vercel →",
    "**Settings** → **Environment Variables**):",
    "",
    "```text",
    "DATABASE_DRIVER        = d1",
    "DATABASE_ID            = <d1-database-id>",
    "CLOUDFLARE_ACCOUNT_ID  = <account-id 32 hex>",
    "CLOUDFLARE_API_TOKEN   = <token dari langkah A3>",
    "```",
    "",
    "## Bagian B - Cloudflare KV (alternatif)",
    "",
    "### B1. Buat namespace",
    "",
    "1. Sidebar → **Storage & Databases** → **KV**.",
    "2. Klik **Create a namespace**.",
    "3. Nama: `katsu-r2-manager`.",
    "4. Salin **Namespace ID** dari daftar - inilah nilai `KV_NAMESPACE_ID`.",
    "",
    "### B2. API token",
    "",
    "Sama seperti langkah **A3**, tetapi izin yang dibutuhkan:",
    "",
    "- `Account` → `Workers KV Storage` → **Edit**",
    "- `Account` → `Account Settings` → **Read**",
    "",
    "### B3. Inisialisasi",
    "",
    "Buka `/admin/settings` → **Initialize database**. Driver KV akan membuat kunci indeks (`idx:files`,",
    "`idx:storages`, `idx:uploads`, `meta:schema`). Tidak ada skema SQL yang perlu dijalankan.",
    "",
    "### B4. Environment variables",
    "",
    "```text",
    "DATABASE_DRIVER   = kv",
    "KV_NAMESPACE_ID   = <namespace-id>",
    "CLOUDFLARE_ACCOUNT_ID = <account-id>",
    "CLOUDFLARE_API_TOKEN  = <token>",
    "```",
    "",
    "## Verifikasi",
    "",
    "Ada tiga cara memastikan database tersambung:",
    "",
    "1. **`/api/health`** - endpoint publik ringan:",
    "",
    "```json",
    "{",
    '  "ok": true,',
    '  "data": {',
    '    "status": "ok",',
    '    "database": { "driver": "d1", "ready": true, "schemaInitialized": true }',
    "  }",
    "}",
    "```",
    "",
    "2. **`/admin/settings` → Diagnostics** - menampilkan driver, jumlah tabel/baris, dan semua environment",
    "   variable yang hilang.",
    "3. **`/admin` (Dashboard)** - kartu statistik akan terisi begitu database siap.",
    "",
    "## Catatan operasional",
    "",
    "- **Backup**: D1 bisa diekspor dari dashboard (D1 → database → **Export**). Lakukan sebelum perubahan besar.",
    "- **Batas ukuran**: satu database D1 gratis berukuran hingga 5 GB - lebih dari cukup untuk ratusan ribu",
    "  baris metadata.",
    "- **Migrasi D1 → KV**: ekspor file sebagai SQL/CSV dari D1, lalu unggah ulang lewat Admin → Upload bila",
    "  Anda pindah driver (metadata dibangun ulang otomatis saat file diupload).",
    "- **Mode demo**: set `DEMO_MODE=true` dan `DATABASE_DRIVER=memory` untuk mencoba UI tanpa Cloudflare.",
    "",
    "## Selanjutnya",
    "",
    "- [Deployment](/docs/deployment) - menjalankan aplikasi di Cloudflare atau Vercel lewat dashboard.",
    "- [Environment Variables](/docs/environment-variables) - daftar lengkap semua variabel.",
  ].join("\n"),
};
