import type { DocPage } from "@/docs/types";

/**
 * Deployment lewat Dashboard
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "deployment",
  title: "Deployment lewat Dashboard",
  group: "Cloudflare",
  order: 40,
  icon: "server",
  description: "Dua jalur deploy tanpa terminal - Cloudflare Workers/Pages memakai OpenNext, atau Vercel dengan import repository - lengkap dengan build command, environment variables, dan custom domain.",
  updated: "2026-09-19",
  body: [
    "Katsu R2 Manager adalah aplikasi Next.js (App Router, TypeScript, Tailwind CSS) yang berjalan di **Node.js",
    "runtime** dan kompatibel dengan **Cloudflare Workers**. Ada dua jalur deploy yang seluruhnya dilakukan dari",
    "dashboard:",
    "",
    "| Jalur | Paling cocok bila | Download besar | Catatan |",
    "| --- | --- | --- | --- |",
    "| **Cloudflare Workers/Pages** | Anda sudah memakai Cloudflare untuk R2 & domain | Sangat baik (edge, tanpa biaya egress) | Build command memakai OpenNext |",
    "| **Vercel** | Anda ingin deploy paling cepat tanpa konfigurasi | Baik (mode `stream`), sangat baik bila memakai `DOWNLOAD_MODE=worker` | Zero config untuk Next.js |",
    "",
    "> [!NOTE] Repository sebagai sumber",
    "> Kedua jalur men-deploy dari repository Git (GitHub). Setelah kode berada di GitHub, semua langkah",
    "> berikutnya - build, deploy, env variables, domain, rollback - dilakukan di dashboard. Tidak perlu",
    "> menjalankan perintah apa pun di komputer Anda.",
    "",
    "## Jalur A - Cloudflare Workers / Pages (OpenNext)",
    "",
    "Repository ini sudah menyertakan `wrangler.jsonc` dan `open-next.config.ts`, jadi Cloudflare tahu cara",
    "membangun aplikasi.",
    "",
    "### A1. Buat Worker dari repository",
    "",
    "1. Buka [dash.cloudflare.com](https://dash.cloudflare.com) → **Compute (Workers)** atau **Workers & Pages**.",
    "2. Klik **Create** → tab **Worker** (atau **Pages** bila Anda memakai Pages) → **Connect to Git**.",
    "3. Beri akses Cloudflare ke repository GitHub Anda (ikuti wizard OAuth) dan pilih repo",
    "   `Katsu-R2-Manager`.",
    "4. Klik **Begin setup**.",
    "",
    "### A2. Build settings",
    "",
    "Isi form build sebagai berikut:",
    "",
    "| Field | Nilai |",
    "| --- | --- |",
    "| **Project name** | `katsu-r2-manager` (harus sama dengan `name` di `wrangler.jsonc`) |",
    "| **Production branch** | `main` |",
    "| **Framework preset** | `Next.js` (bila tersedia) |",
    "| **Build command** | `npx opennextjs-cloudflare build` |",
    "| **Build output directory** | *(kosongkan - `wrangler.jsonc` sudah menunjuk `.open-next`)* |",
    "| **Root directory** | `/` |",
    "",
    "5. Klik **Save and Deploy**. Build pertama biasanya 2-5 menit.",
    "",
    "> [!TIP] Worker name harus sama",
    "> `wrangler.jsonc` memuat binding `WORKER_SELF_REFERENCE` yang dipakai adapter OpenNext untuk routing",
    "> internal. Bila Anda mengganti `name` di dashboard, ubah juga nilai `name` dan `services[0].service` di",
    "> `wrangler.jsonc` agar tidak muncul error 500.",
    "",
    "### A3. Variables and Secrets",
    "",
    "Buka Worker Anda → **Settings** → **Variables and Secrets** → **Add**:",
    "",
    "- Tipe **Text** (boleh terlihat): `DATABASE_DRIVER`, `DATABASE_ID`, `CLOUDFLARE_ACCOUNT_ID`, `APP_URL`,",
    "  `DOWNLOAD_MODE`, `ADMIN_USERNAME`, `PUBLIC_LISTING`, `STORAGE_OBJECT_PREFIX`, `MAX_UPLOAD_SIZE_GB`,",
    "  `DEFAULT_PART_SIZE_MB`, `SESSION_TTL_HOURS`, `LOG_LEVEL`.",
    "- Tipe **Secret** (terenkripsi): `ADMIN_PASSWORD_HASH`, `SESSION_SECRET`, `CREDENTIAL_ENCRYPTION_KEY`,",
    "  `CLOUDFLARE_API_TOKEN`.",
    "",
    "Klik **Deploy** setelah menambah variabel agar nilai baru aktif.",
    "",
    "### A4. Batas CPU (penting untuk login)",
    "",
    "Verifikasi password memakai PBKDF2 yang membutuhkan waktu CPU nyata. Worker **free plan** dibatasi 10 ms",
    "CPU per request, sedangkan `wrangler.jsonc` proyek ini meminta `limits.cpu_ms = 30000`.",
    "",
    "- **Paket berbayar (Workers Paid, mulai $5)**: nilai 30000 diterima, login nyaman dengan 100.000 iterasi.",
    "- **Paket gratis**: bila login gagal dengan *exceeded CPU*, buka **Setup Assistant** (`/setup`) dan buat",
    "  ulang `ADMIN_PASSWORD_HASH` dengan preset **Cloudflare Free (25.000 iterasi)** atau lebih rendah.",
    "  Rate limiter dan session HMAC tetap menjaga keamanan.",
    "",
    "### A5. Custom domain",
    "",
    "1. Worker Anda → **Settings** → **Domains & Routes** → **Add** → **Custom domain**.",
    "2. Ketik `download.domain.com` (zona harus sudah ada di akun Cloudflare yang sama).",
    "3. Cloudflare otomatis membuat record DNS dan sertifikat SSL.",
    "4. Setelah aktif, isi `APP_URL=https://download.domain.com` dan tambahkan origin ini ke CORS policy bucket",
    "   R2 (lihat [Cloudflare R2 Setup](/docs/r2-setup)).",
    "",
    "## Jalur B - Vercel",
    "",
    "### B1. Import repository",
    "",
    "1. Buka [vercel.com/new](https://vercel.com/new) dan login.",
    "2. Klik **Import** pada repository `Katsu-R2-Manager` (beri akses Vercel ke GitHub bila diminta).",
    "3. Vercel otomatis mendeteksi framework **Next.js**.",
    "",
    "### B2. Build & Output settings",
    "",
    "Biarkan default:",
    "",
    "| Field | Nilai |",
    "| --- | --- |",
    "| **Framework Preset** | Next.js |",
    "| **Build Command** | `next build` (default) |",
    "| **Output Directory** | `.next` (default) |",
    "| **Install Command** | `npm install` (default) |",
    "| **Node.js Version** | 20.x atau lebih baru |",
    "",
    "### B3. Environment variables",
    "",
    "Pada langkah **Configure Environment Variables**, tambahkan kunci yang sama seperti jalur A. Semua variabel",
    "di Vercel otomatis dienkripsi; centang **Sensitive** untuk `ADMIN_PASSWORD_HASH`, `SESSION_SECRET`,",
    "`CREDENTIAL_ENCRYPTION_KEY`, dan `CLOUDFLARE_API_TOKEN` agar tidak bisa dilihat lagi setelah disimpan.",
    "",
    "### B4. Deploy",
    "",
    "Klik **Deploy**. Setelah selesai:",
    "",
    "1. Buka **Settings** → **Domains** → tambahkan `download.domain.com` dan ikuti petunjuk DNS di registrar",
    "   Anda (atau arahkan ke Cloudflare dengan proxy aktif).",
    "2. Isi `APP_URL` sesuai domain final, lalu **Redeploy** (Deployments → ⋯ → Redeploy).",
    "",
    "### B5. Rekomendasi untuk file besar di Vercel",
    "",
    "Fungsi serverless memiliki batas durasi. Untuk file berukuran gigabyte:",
    "",
    "- Pakai `DOWNLOAD_MODE=stream` untuk file sampai beberapa ratus MB.",
    "- Untuk file sangat besar, deploy **download worker** opsional di Cloudflare dan set",
    "  `DOWNLOAD_MODE=worker` + `DOWNLOAD_WORKER_URL`. Aplikasi akan mengalihkan unduhan ke worker edge",
    "  Cloudflare (lihat [Download System](/docs/download-system)).",
    "",
    "## Setelah deploy: urutan aktivasi",
    "",
    "1. Buka `https://domain-anda/setup` → **Setup Assistant**.",
    "   - Buat `ADMIN_PASSWORD_HASH` (password diproses di browser, tidak dikirim ke server).",
    "   - Generate `SESSION_SECRET` dan `CREDENTIAL_ENCRYPTION_KEY`.",
    "   - Salin semuanya ke dashboard hosting sebagai Variables/Secrets, lalu redeploy.",
    "2. Buka `/admin/login` → masuk dengan `ADMIN_USERNAME` + password tadi.",
    "3. Buka **Admin → Settings → Database** → klik **Initialize database**.",
    "4. Buka **Admin → Storage** → tambahkan akun R2 pertama → **Test koneksi**.",
    "5. Buka **Admin → Upload** → unggah file uji → salin link download-nya.",
    "6. Buka `/` → pastikan file muncul di Download Center.",
    "",
    "## Update aplikasi",
    "",
    "- **Cloudflare**: setiap push ke branch produksi memicu build & deploy otomatis. Rollback tersedia di tab",
    "  **Deployments**.",
    "- **Vercel**: sama - push ke `main` memicu production deployment; pull request mendapat preview URL.",
    "- Perubahan environment variable **tidak** memicu redeploy otomatis di Cloudflare: klik **Deploy** setelah",
    "  mengubah variabel.",
    "",
    "## Memeriksa kesehatan",
    "",
    "| Endpoint | Fungsi |",
    "| --- | --- |",
    "| `/api/health` | Status konfigurasi, driver database, mode download |",
    "| `/admin/settings` | Diagnostics lengkap + daftar env yang hilang + generator hash |",
    "| Log platform | Vercel → **Observability/Logs**; Cloudflare → **Workers → Logs** |",
    "",
    "## Selanjutnya",
    "",
    "- [Environment Variables](/docs/environment-variables) - arti setiap variabel.",
    "- [Menambahkan Storage](/docs/add-storage) - menyambungkan akun R2 pertama.",
    "- [Troubleshooting](/docs/troubleshooting) - bila deploy gagal.",
  ].join("\n"),
};
