import type { DocPage } from "@/docs/types";

/**
 * Download System
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "download-system",
  title: "Download System",
  group: "Panduan Admin",
  order: 90,
  icon: "download",
  description: "Cara kerja endpoint download publik - streaming dengan HTTP Range, dukungan resume dan download manager, tiga mode download (stream/redirect/worker), serta header dan rate limiting.",
  updated: "2026-09-19",
  body: [
    "Download Center adalah satu-satunya bagian sistem yang dilihat pengguna. Semua permintaan download masuk",
    "melalui satu endpoint:",
    "",
    "```text",
    "GET  /download/<downloadId>",
    "HEAD /download/<downloadId>",
    "```",
    "",
    "`downloadId` adalah identifier publik pendek (10 karakter, tanpa karakter yang membingungkan seperti `0/O`",
    "atau `1/l`). Ia tidak membocorkan urutan, jumlah file, atau lokasi penyimpanan.",
    "",
    "## Alur sebuah permintaan download",
    "",
    "1. `downloadId` dicari di database → diperoleh metadata file.",
    "2. Dari metadata diketahui `storageId`, `bucket`, dan `objectKey` (semuanya tetap di server).",
    "3. Server membangun client R2 untuk storage tersebut dan menandatangani request S3 (SigV4).",
    "4. Byte dialirkan dari R2 ke pengunjung (**pass-through streaming**, tidak dibuffer di memori).",
    "5. Header yang dibutuhkan resume dikembalikan apa adanya: `Accept-Ranges`, `Content-Range`,",
    "   `Content-Length`, `ETag`, `Last-Modified`.",
    "6. Penghitung unduhan dinaikkan (sekali per unduhan baru, bukan per range request).",
    "",
    "Yang **tidak pernah** terlihat oleh pengunjung: Account ID, nama bucket, object key, Access Key ID, Secret",
    "Access Key, dan endpoint R2.",
    "",
    "## HTTP Range & resume",
    "",
    "Endpoint menerima header `Range: bytes=<start>-<end>` dan menjawab `206 Partial Content` dengan",
    "`Content-Range` yang benar. Dukungan ini membuat:",
    "",
    "- **Download manager** (IDM, FDM, JDownloader, aria2) bisa memecah file menjadi banyak koneksi,",
    "- **Video player** bisa melompat ke posisi tertentu tanpa mengunduh seluruh file,",
    "- **Unduhan yang terputus** bisa dilanjutkan dari byte terakhir (`Resume`),",
    "- **Browser mobile** bisa meneruskan unduhan setelah jaringan berpindah.",
    "",
    "Range bentuk akhir juga didukung: `Range: bytes=-1048576` meminta 1 MB terakhir.",
    "",
    "Untuk menguji resume dari browser, buka halaman detail file lalu gunakan tombol download - bila koneksi",
    "terputus, download manager akan melanjutkan otomatis karena `Accept-Ranges: bytes` dikirim.",
    "",
    "## Tiga mode download",
    "",
    "Atur lewat `DOWNLOAD_MODE`:",
    "",
    "| Mode | Cara kerja | Privasi | Cocok untuk |",
    "| --- | --- | --- | --- |",
    "| `stream` (default) | Aplikasi meneruskan byte dari R2 | Terbaik - tidak ada detail R2 yang keluar | Cloudflare Workers/Pages, Vercel dengan file sampai ratusan MB |",
    "| `redirect` | Aplikasi membalas `302` ke pre-signed URL R2 (berlaku 15 menit) | Lebih rendah - URL sementara memuat account id & bucket | Hosting dengan batas durasi fungsi yang ketat |",
    "| `worker` | Aplikasi membalas `302` ke download worker Cloudflare dengan token bertanda tangan | Sangat baik - worker menyembunyikan detail R2 | Vercel + file sangat besar (transfer dipindah ke edge Cloudflare) |",
    "",
    "### Mode `worker` (opsional, disarankan untuk Vercel + file raksasa)",
    "",
    "Folder `workers/` berisi Worker mandiri `download-worker.ts` yang:",
    "",
    "- memverifikasi token HMAC dari aplikasi,",
    "- membaca metadata dari D1 HTTP API,",
    "- menandatangani request ke R2 dan mengalirkan byte dengan dukungan Range penuh.",
    "",
    "Deploy dari dashboard Cloudflare (Workers → Create → paste kode, atau lewat repository), pasang domain",
    "misalnya `dl.domain.com`, lalu set:",
    "",
    "```text",
    "DOWNLOAD_MODE=worker",
    "DOWNLOAD_WORKER_URL=https://dl.domain.com",
    "DOWNLOAD_SIGNING_SECRET=<secret yang sama di Worker>",
    "```",
    "",
    "Dengan susunan ini, fungsi di Vercel hanya menerbitkan redirect kecil; transfer data berat terjadi di edge",
    "Cloudflare yang tidak memungut egress.",
    "",
    "## Header yang dikirim",
    "",
    "```text",
    "Content-Type:        <tipe file>",
    "Content-Disposition: attachment; filename=\"nama-aman.ext\"; filename*=UTF-8''nama-asli.ext",
    "Content-Length:      <ukuran atau ukuran range>",
    "Accept-Ranges:       bytes",
    "Content-Range:       bytes 0-1048575/52428800   (hanya untuk 206)",
    "ETag:                <etag dari R2>",
    "Last-Modified:       <waktu objek>",
    "Cache-Control:       private, max-age=0, must-revalidate",
    "X-Content-Type-Options: nosniff",
    "```",
    "",
    "`Content-Disposition` memakai RFC 5987 (`filename*`) sehingga nama file berbahasa Indonesia, Jepang, atau",
    "ber-spasi tetap benar di semua browser. Set `DOWNLOAD_INLINE_CONTENT_TYPES=true` bila Anda lebih suka",
    "browser membuka file (misalnya PDF/gambar) alih-alih mengunduhnya.",
    "",
    "## Rate limiting",
    "",
    "`RATE_LIMIT_DOWNLOAD_REQUESTS` (default 120 per menit per IP) membatasi jumlah permintaan download,",
    "termasuk range request. Respons `429` menyertakan header `Retry-After`. Daftar file publik dibatasi",
    "`RATE_LIMIT_API_REQUESTS`.",
    "",
    "## Halaman terkait",
    "",
    "| URL | Isi |",
    "| --- | --- |",
    "| `/` | Download Center: pencarian, filter kategori, urutan, pagination |",
    "| `/file/<downloadId>` | Halaman detail file + tombol download, salin link, dan bagikan |",
    "| `/download/<downloadId>` | Endpoint byte (streaming) |",
    "| `/download/<downloadId>?info=1` | JSON ringkas metadata publik (untuk integrasi) |",
    "| `/download/<downloadId>?inline=1` | Unduh dengan `Content-Disposition: inline` |",
    "",
    "## Menonaktifkan daftar publik",
    "",
    "Set `PUBLIC_LISTING=false` bila Anda ingin link tetap berfungsi tetapi daftar file disembunyikan. Dalam mode",
    "ini `/` menampilkan keadaan kosong dan `/api/public/files` menolak dengan `listing_disabled`, sementara",
    "`/download/<id>` tetap melayani siapa pun yang memiliki link.",
    "",
    "## Selanjutnya",
    "",
    "- [Security Guide](/docs/security) - detail proteksi endpoint publik.",
    "- [Troubleshooting](/docs/troubleshooting) - unduhan lambat atau gagal.",
  ].join("\n"),
};
