import type { DocPage } from "@/docs/types";

/**
 * Environment Variables
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "environment-variables",
  title: "Environment Variables",
  group: "Cloudflare",
  order: 50,
  icon: "key",
  description: "Referensi lengkap seluruh environment variable Katsu R2 Manager - mana yang wajib, nilai default, contoh, dan cara mengisinya di dashboard Cloudflare maupun Vercel.",
  updated: "2026-09-19",
  body: [
    "Semua konfigurasi dilakukan lewat environment variables. Tidak ada file konfigurasi yang perlu diedit di",
    "server, dan tidak ada perintah yang perlu dijalankan.",
    "",
    "Cara mengisi:",
    "",
    "- **Cloudflare**: Worker/Pages Anda → **Settings** → **Variables and Secrets** → **Add**. Gunakan tipe",
    "  **Secret** untuk nilai sensitif. Klik **Deploy** setelah selesai.",
    "- **Vercel**: Project → **Settings** → **Environment Variables** → tambahkan untuk **Production**,",
    "  **Preview**, dan **Development**. Centang **Sensitive** untuk nilai sensitif, lalu **Redeploy**.",
    "",
    "Salin template dari file `.env.example` di repository sebagai daftar periksa.",
    "",
    "## Wajib (aplikasi tidak berfungsi tanpanya)",
    "",
    "| Variable | Contoh | Keterangan |",
    "| --- | --- | --- |",
    "| `ADMIN_USERNAME` | `katsu` | Username login admin. Default `katsu`. |",
    "| `ADMIN_PASSWORD_HASH` | `pbkdf2-sha256$100000$...` | Hash password. Buat di halaman **Setup Assistant** (`/setup`). |",
    "| `SESSION_SECRET` | *(64 karakter acak)* | Menandatangani session cookie. Minimal 32 karakter. |",
    "| `CREDENTIAL_ENCRYPTION_KEY` | *(64 karakter acak)* | Mengenkripsi Secret Access Key R2 di database (AES-256-GCM). |",
    "| `CLOUDFLARE_ACCOUNT_ID` | `a1b2c3...` (32 hex) | Akun tempat D1/KV berada. |",
    "| `CLOUDFLARE_API_TOKEN` | *(token)* | Token API dengan izin **D1: Edit** (atau **KV: Edit**). |",
    "| `DATABASE_ID` | `9f2c...` (UUID) | ID database D1. Wajib bila `DATABASE_DRIVER=d1`. |",
    "",
    "## Database",
    "",
    "| Variable | Default | Keterangan |",
    "| --- | --- | --- |",
    "| `DATABASE_DRIVER` | `d1` | `d1`, `kv`, atau `memory`. Bila identifier yang sesuai kosong, aplikasi otomatis jatuh ke driver lain yang tersedia dan mencatat peringatannya. |",
    "| `DATABASE_ID` | - | ID database D1 (lihat [Database Setup](/docs/database-setup)). |",
    "| `KV_NAMESPACE_ID` | - | ID namespace KV, dipakai bila `DATABASE_DRIVER=kv`. |",
    "| `CLOUDFLARE_API_BASE_URL` | `https://api.cloudflare.com/client/v4` | Hanya perlu diubah untuk deployment khusus/enterprise. |",
    "",
    "## Admin & keamanan",
    "",
    "| Variable | Default | Keterangan |",
    "| --- | --- | --- |",
    "| `ADMIN_USERNAME` | `katsu` | Dibandingkan secara *constant-time*. |",
    "| `ADMIN_PASSWORD_HASH` | - | Format `pbkdf2-sha256$<iterasi>$<salt>$<hash>`. |",
    "| `PASSWORD_PBKDF2_ITERATIONS` | `100000` | Dipakai saat membuat hash baru. Gunakan 25.000 atau lebih rendah di Workers free plan. |",
    "| `SESSION_SECRET` | - | Kunci HMAC untuk session cookie dan link download bertanda tangan. |",
    '| `SESSION_TTL_HOURS` | `12` | Umur sesi. Opsi "ingat saya" memperpanjang sampai 7 hari (maks 30 hari). |',
    "| `SESSION_COOKIE_NAME` | `katsu_session` | Ganti bila bentrok dengan aplikasi lain di domain yang sama. |",
    "| `CSRF_COOKIE_NAME` | `katsu_csrf` | Cookie CSRF (double submit). |",
    "| `CREDENTIAL_ENCRYPTION_KEY` | - | 32 byte dalam hex/base64, atau passphrase (akan diturunkan dengan SHA-256). |",
    "",
    "## Aplikasi",
    "",
    "| Variable | Default | Keterangan |",
    "| --- | --- | --- |",
    "| `APP_NAME` | `Katsu R2 Manager` | Nama yang tampil di UI dan metadata. |",
    "| `APP_URL` | - | Origin publik, misal `https://download.domain.com`. Dipakai untuk link absolut. |",
    "| `DEMO_MODE` | `false` | `true` = data contoh in-memory, upload/download R2 dinonaktifkan. |",
    "| `LOG_LEVEL` | `info` | `debug`, `info`, `warn`, `error`. Log berbentuk JSON dan otomatis menyensor field sensitif. |",
    "",
    "## Storage pool",
    "",
    "| Variable | Default | Keterangan |",
    "| --- | --- | --- |",
    "| `STORAGE_OBJECT_PREFIX` | `files` | Prefiks object key di dalam bucket (`files/2026/09/...`). |",
    "| `DEFAULT_PART_SIZE_MB` | `8` | Ukuran part multipart. Diperbesar otomatis bila file sangat besar agar tidak melebihi 10.000 part. Minimum efektif 5 MB. |",
    "| `MAX_UPLOAD_SIZE_GB` | `20` | Batas ukuran satu file. R2 sendiri mendukung hingga 5 TiB per object. |",
    "| `MAX_CONCURRENT_PARTS` | `3` | Jumlah part yang diunggah browser secara paralel per file. |",
    "| `STORAGE_PROBE_KEY` | `.katsu/connection-probe.txt` | Object uji yang ditulis & dihapus saat **Test koneksi**. |",
    "",
    "## Download",
    "",
    "| Variable | Default | Keterangan |",
    "| --- | --- | --- |",
    "| `DOWNLOAD_MODE` | `stream` | `stream` (proxy, paling privat), `redirect` (pre-signed URL R2), atau `worker` (diteruskan ke download worker). |",
    "| `DOWNLOAD_WORKER_URL` | - | URL worker, wajib bila `DOWNLOAD_MODE=worker`. |",
    "| `DOWNLOAD_SIGNING_SECRET` | *(= `SESSION_SECRET`)* | Kunci penanda tautan download untuk mode `worker`/`redirect`. |",
    "| `DOWNLOAD_LINK_TTL_SECONDS` | `21600` | Umur link bertanda tangan (6 jam). Pre-signed URL R2 tetap dibatasi 15 menit. |",
    "| `PUBLIC_LISTING` | `true` | `false` = Download Center tidak menampilkan daftar file (link langsung tetap berfungsi). |",
    "| `DOWNLOAD_INLINE_CONTENT_TYPES` | `false` | `true` = kirim `Content-Disposition: inline` sehingga browser membuka file alih-alih mengunduh. |",
    "",
    "## Rate limiting",
    "",
    "| Variable | Default | Keterangan |",
    "| --- | --- | --- |",
    "| `RATE_LIMIT_LOGIN_ATTEMPTS` | `6` | Percobaan login per window sebelum diblokir sementara. |",
    "| `RATE_LIMIT_LOGIN_WINDOW_SECONDS` | `900` | Panjang window login (15 menit). |",
    "| `RATE_LIMIT_API_REQUESTS` | `240` | Request API admin per window. |",
    "| `RATE_LIMIT_API_WINDOW_SECONDS` | `60` | Panjang window API. |",
    "| `RATE_LIMIT_DOWNLOAD_REQUESTS` | `120` | Request download per IP per window (menghitung juga range request). |",
    "| `RATE_LIMIT_DOWNLOAD_WINDOW_SECONDS` | `60` | Panjang window download. |",
    "",
    "Counter rate limit disimpan di database (`app_state`) sehingga berlaku lintas instance. Khusus download,",
    "counter memakai memori per isolate agar range request beruntun tidak membebani database.",
    "",
    "## Contoh set minimum untuk produksi",
    "",
    "```text",
    "APP_NAME=Katsu R2 Manager",
    "APP_URL=https://download.domain.com",
    "",
    "ADMIN_USERNAME=katsu",
    "ADMIN_PASSWORD_HASH=pbkdf2-sha256$100000$<salt>$<hash>",
    "SESSION_SECRET=<64 karakter acak>",
    "CREDENTIAL_ENCRYPTION_KEY=<64 karakter acak>",
    "SESSION_TTL_HOURS=12",
    "",
    "CLOUDFLARE_ACCOUNT_ID=<account-id>",
    "CLOUDFLARE_API_TOKEN=<token D1 Edit>",
    "DATABASE_DRIVER=d1",
    "DATABASE_ID=<d1-database-id>",
    "",
    "DOWNLOAD_MODE=stream",
    "PUBLIC_LISTING=true",
    "MAX_UPLOAD_SIZE_GB=20",
    "DEFAULT_PART_SIZE_MB=8",
    "LOG_LEVEL=info",
    "```",
    "",
    "> [!WARNING] Setelah mengubah variabel, redeploy",
    "> Cloudflare tidak memuat ulang variabel sampai Anda menekan **Deploy**; Vercel memerlukan **Redeploy**.",
    "> Halaman **Admin → Settings → Diagnostics** menampilkan variabel mana yang masih kosong.",
    "",
    "## Selanjutnya",
    "",
    "- [Deployment](/docs/deployment) - tempat mengisi variabel ini.",
    "- [Security Guide](/docs/security) - alasan tiap secret dibutuhkan.",
  ].join("\n"),
};
