import type { DocPage } from "@/docs/types";

/**
 * FAQ
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "faq",
  title: "FAQ",
  group: "Referensi",
  order: 120,
  icon: "help",
  description: "Pertanyaan yang paling sering diajukan tentang Katsu R2 Manager - tanpa CLI, biaya, batas ukuran, keamanan link, multi akun, D1 vs KV, backup, dan cara mengganti password.",
  updated: "2026-09-19",
  body: [
    "## Umum",
    "",
    "### Apakah saya perlu terminal, CLI, npm, wrangler, git, atau VPS?",
    "",
    "Tidak. Seluruh alur - membuat bucket, membuat token, mengisi environment variables, membuat tabel",
    "database, deploy, sampai mengelola file - dilakukan lewat **Cloudflare Dashboard**, **Vercel Dashboard**,",
    "dan **browser**. README dan dokumentasi ini sengaja tidak memuat satu pun perintah terminal untuk",
    "pengguna.",
    "",
    "### Apakah ini gratis?",
    "",
    "Komponennya memiliki kuota gratis:",
    "",
    "| Komponen | Kuota gratis |",
    "| --- | --- |",
    "| Cloudflare R2 | 10 GB penyimpanan per akun, 1 juta operasi Class A, 10 juta operasi Class B, **egress gratis** |",
    "| Cloudflare D1 | 5 GB penyimpanan, 5 juta baris dibaca per hari |",
    "| Cloudflare KV | 100.000 operasi baca/hari, 1.000 tulis/hari |",
    "| Cloudflare Workers | 100.000 request/hari (paket free) |",
    "| Vercel | Paket Hobby (non-komersial) |",
    "",
    "Dengan tiga akun Cloudflare, Anda mendapat pool 30 GB tanpa biaya egress - inilah alasan sistem ini",
    "dirancang untuk banyak akun.",
    "",
    "### Kenapa menggabungkan banyak akun R2?",
    "",
    "Karena kuota gratis diberikan **per akun**. Menggabungkan tiga akun 10 GB memberi satu drive 30 GB yang",
    "terlihat seperti satu sistem, tanpa pengguna akhir menyadari ada tiga bucket di belakangnya.",
    "",
    "### Apakah pengguna bisa tahu file berada di akun R2 mana?",
    "",
    "Tidak. Endpoint publik hanya menerima `downloadId` acak. Account ID, nama bucket, dan object key tidak",
    "pernah dikirim ke browser pada mode `stream` (default). Pengecualian: mode `redirect` memakai pre-signed",
    "URL R2 yang memuat nama bucket dan account id selama 15 menit - karena itu mode default adalah `stream`.",
    "",
    "### Bisakah memakai domain sendiri?",
    "",
    "Bisa. Arahkan misalnya `download.domain.com` ke Worker (Cloudflare → **Domains & Routes** → Custom domain)",
    "atau ke Vercel (Settings → Domains). Setelah aktif, isi `APP_URL` dan tambahkan origin tersebut ke CORS",
    "policy bucket.",
    "",
    "## Batas & kemampuan",
    "",
    "### Berapa ukuran file maksimum?",
    "",
    "Secara default 20 GB per file (`MAX_UPLOAD_SIZE_GB`), dan R2 sendiri mendukung hingga 5 TiB per object.",
    "Upload memakai multipart dengan maksimum 10.000 part; bila perlu, ukuran part diperbesar otomatis.",
    "",
    "### Apakah file 5 GB+ benar-benar didukung?",
    "",
    "Ya. Byte mengalir **langsung dari browser ke R2** melalui pre-signed URL per part, sehingga server aplikasi",
    "tidak pernah menampung file di RAM dan tidak terkena batas ukuran body platform hosting.",
    "",
    "### Apakah upload bisa dilanjutkan setelah koneksi putus atau halaman ditutup?",
    "",
    "Bisa. Antrean tersimpan di IndexedDB browser dan sesi multipart tersimpan di server. Saat kembali ke",
    "`/admin/upload`, sistem memanggil `ListParts` ke R2 untuk mengetahui part mana yang sudah tersimpan dan",
    "melanjutkan dari part berikutnya.",
    "",
    "### Berapa banyak storage yang bisa ditambahkan?",
    "",
    "Tidak ada batas di sisi aplikasi. Praktisnya dibatasi jumlah akun Cloudflare yang Anda kelola.",
    "",
    "### Apakah bisa upload folder?",
    "",
    "Bisa, lewat tombol **Upload folder** (memakai pemilih direktori browser). Struktur folder diratakan menjadi",
    "nama file yang aman - object key tetap unik karena memakai id sesi.",
    "",
    "### Apakah ada aplikasi mobile?",
    "",
    "Tidak perlu. Antarmuka dirancang *mobile first* dan bisa di-install sebagai aplikasi lewat manifest PWA",
    "(**Add to Home Screen** di iOS/Android).",
    "",
    "## Database",
    "",
    "### Pilih D1 atau KV?",
    "",
    "**D1** untuk hampir semua kasus: query terindeks, konsisten, dan bisa diekspor. **KV** hanya bila Anda ingin",
    "setup paling sederhana untuk library kecil (beberapa ratus file). Driver dipilih lewat `DATABASE_DRIVER`.",
    "",
    "### Apakah bisa pindah dari KV ke D1 nanti?",
    "",
    "Bisa. Siapkan D1, jalankan **Initialize database**, lalu ubah `DATABASE_DRIVER=d1` dan isi `DATABASE_ID`.",
    "Objek di R2 tidak berpindah; yang perlu dilakukan hanyalah mengunggah ulang metadata (atau memindahkan file",
    "lewat File Manager agar metadata baru tercatat di D1).",
    "",
    "### Apa isi database-nya?",
    "",
    "Empat tabel utama: `storages` (kredensial terenkripsi + kuota), `files` (metadata + lokasi objek +",
    "`download_id` publik), `upload_sessions` (status multipart untuk resume), dan `app_state` (rate limit, job",
    "pemindahan). Ditambah `meta` untuk versi skema.",
    "",
    "### Apakah data file disimpan di database?",
    "",
    "Tidak. Database hanya menyimpan metadata. Byte file selalu berada di R2.",
    "",
    "## Keamanan",
    "",
    "### Bagaimana password admin disimpan?",
    "",
    "Sebagai hash **PBKDF2-SHA256** dengan salt acak, di environment variable `ADMIN_PASSWORD_HASH`. Hash dibuat",
    "di browser Anda melalui `/setup`, jadi password tidak pernah dikirim ke server maupun disimpan di database.",
    "",
    "### Bagaimana kredensial R2 dilindungi?",
    "",
    "Secret Access Key dienkripsi **AES-256-GCM** dengan `CREDENTIAL_ENCRYPTION_KEY` sebelum masuk database, dan",
    "hanya didekripsi di memori server saat menandatangani request S3. API tidak pernah mengirimkannya ke",
    "browser; Access Key ID pun hanya muncul tersamar.",
    "",
    "### Apakah ada proteksi brute force?",
    "",
    "Ya. Login dibatasi 6 percobaan per 15 menit untuk kombinasi IP+username, disimpan di database sehingga",
    "berlaku lintas instance. Setelah berhasil login, penghitung dibersihkan.",
    "",
    "### Apakah link download bisa kedaluwarsa?",
    "",
    "Link publik `/download/<id>` tidak kedaluwarsa (selama file ada dan berstatus publik). Yang berumur pendek",
    "adalah URL internal: pre-signed URL upload part (6 jam) dan pre-signed URL mode `redirect` (15 menit).",
    "",
    "### Bisakah membuat file tidak muncul di daftar publik tapi tetap bisa diunduh?",
    "",
    "Bisa. Set visibilitas file menjadi **Privat**, atau set `PUBLIC_LISTING=false` untuk menyembunyikan seluruh",
    "daftar. Link langsung tetap berfungsi sesuai visibilitasnya.",
    "",
    "### Apakah isi file dienkripsi end-to-end?",
    "",
    "Tidak. R2 mengenkripsi data saat disimpan di sisi Cloudflare, tetapi aplikasi tidak mengenkripsi isi file.",
    "Untuk data sangat sensitif, enkripsi/arshipkan file sebelum upload.",
    "",
    "## Operasional",
    "",
    "### Bagaimana cara mengganti password admin?",
    "",
    "Buka `/setup`, buat hash dari password baru, lalu perbarui `ADMIN_PASSWORD_HASH` di dashboard hosting dan",
    "redeploy. Untuk memutus semua sesi aktif, ganti juga `SESSION_SECRET`.",
    "",
    "### Bagaimana cara membackup sistem?",
    "",
    "Objek ada di R2 (backup lewat kebijakan akun Cloudflare Anda). Metadata bisa diekspor dari dashboard D1",
    "(**Export**). Environment variables sebaiknya disimpan di password manager.",
    "",
    "### Bagaimana cara menghapus semua data?",
    "",
    "1. Hapus file lewat File Manager (objek di R2 ikut terhapus).",
    "2. Kosongkan bucket dari dashboard R2 bila perlu.",
    "3. Hapus database D1/namespace KV dari dashboard.",
    "4. Hapus aplikasi dari dashboard hosting.",
    "",
    "### Apakah bisa dipakai banyak orang (multi-user)?",
    "",
    "Sistem dirancang untuk satu operator. Download Center bersifat publik; panel admin dilindungi satu",
    "kredensial. Menambah banyak pengguna memerlukan tabel pengguna, peran, dan audit log tersendiri.",
    "",
    "### Apakah bisa self-host tanpa Cloudflare/Vercel?",
    "",
    "Kode ini Next.js standar, jadi secara teknis bisa dijalankan di mana pun Node.js tersedia. Namun proyek ini",
    'dirancang khusus untuk deployment lewat dashboard Cloudflare/Vercel - sesuai kebutuhan "tanpa VPS".',
    "",
    "### Kenapa ada folder `workers/` bila aplikasi sudah berjalan di Cloudflare?",
    "",
    "Itu komponen **opsional**: download worker mandiri untuk memindahkan beban transfer file besar ke edge",
    "Cloudflare (sangat berguna bila aplikasi utama berada di Vercel). Deploy hanya bila Anda memakai",
    "`DOWNLOAD_MODE=worker`.",
    "",
    "### Apakah ada biaya tersembunyi?",
    "",
    "Tidak dari sisi aplikasi. Biaya yang mungkin muncul berasal dari Cloudflare/Vercel bila pemakaian melewati",
    "kuota gratis (misalnya operasi Class A yang sangat banyak, atau Workers Paid untuk CPU lebih besar).",
    "",
    "## Selanjutnya",
    "",
    "- [Getting Started](/docs/getting-started)",
    "- [Security Guide](/docs/security)",
    "- [Troubleshooting](/docs/troubleshooting)",
  ].join("\n"),
};
