import type { DocPage } from "@/docs/types";

/**
 * File Management
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "file-management",
  title: "File Management",
  group: "Panduan Admin",
  order: 80,
  icon: "folder",
  description: "Memakai File Manager admin - mencari, mengurutkan, rename, menghapus, mengubah visibilitas, menyalin link, melihat lokasi storage, dan memindahkan file antar akun R2.",
  updated: "2026-09-19",
  body: [
    "**File Manager** (`/admin/files`) menampilkan seluruh isi storage pool dalam satu tabel, apa pun akun R2",
    "tempat file itu berada.",
    "",
    "## Isi tabel",
    "",
    "| Kolom | Keterangan |",
    "| --- | --- |",
    "| Nama file | Nama tampilan (sudah disanitasi saat upload) |",
    "| Ukuran | Ukuran sebenarnya yang diverifikasi dari R2 saat upload selesai |",
    "| Tipe | Kategori otomatis (video, arsip, dokumen, dan lain-lain) |",
    "| Storage | Nama storage tempat file berada + statusnya |",
    "| Unduhan | Jumlah kali file diunduh publik |",
    "| Visibilitas | Publik / Privat |",
    "| Dibuat | Waktu upload |",
    "",
    "Baris menampilkan aksi: **Detail**, **Rename**, **Visibilitas**, **Salin link**, **Pindahkan**, **Hapus**.",
    "",
    "## Mencari & memfilter",
    "",
    "- Kotak pencarian mencocokkan nama file dan nama asli (mendukung banyak kata, misalnya `ubuntu iso`).",
    "- Filter **Storage** mempersempit ke satu akun R2 - berguna saat ingin mengosongkan storage tertentu.",
    "- Filter **Visibilitas** memisahkan file publik dan privat.",
    "- Urutkan berdasarkan tanggal, nama, ukuran, atau jumlah unduhan (klik header kolom).",
    "- Pagination 25 baris per halaman (bisa diubah sampai 200).",
    "",
    "## Rename",
    "",
    "Rename mengubah **nama tampilan** dan nama file yang diterima pengguna saat mengunduh",
    "(`Content-Disposition`). Object key di dalam bucket **tidak** diubah, sehingga:",
    "",
    "- operasi selesai seketika tanpa memindahkan data,",
    "- link download lama tetap berlaku,",
    "- riwayat dan jumlah unduhan tidak hilang.",
    "",
    "Nama disanitasi otomatis: karakter kontrol, pemisah jalur (`/`, `\\`), dan nama terlarang Windows",
    "(`CON`, `NUL`, `COM1`, ...) dinetralkan, panjang dibatasi 180 karakter.",
    "",
    "## Visibilitas",
    "",
    "- **Publik** - muncul di Download Center dan dapat diunduh siapa pun yang punya link.",
    "- **Privat** - tidak muncul di daftar publik; `/download/<id>` hanya melayani permintaan dari sesi admin",
    "  yang sedang login. Cocok untuk backup pribadi.",
    "",
    "Perubahan visibilitas berlaku seketika dan tidak memutus link yang sudah dibagikan (untuk file privat, link",
    "hanya berfungsi bagi admin).",
    "",
    "## Menyalin link",
    "",
    "Tombol salin menghasilkan URL absolut berbasis `APP_URL` (atau origin request bila `APP_URL` kosong),",
    "misalnya:",
    "",
    "```text",
    "https://download.domain.com/download/4kd92mxpa1",
    "```",
    "",
    "Ada juga tombol **Bagikan** yang memakai Web Share API di perangkat mobile (WhatsApp, Telegram, dan",
    "sebagainya) dan otomatis jatuh ke salin-link bila tidak tersedia.",
    "",
    "## Melihat lokasi storage",
    "",
    "Panel detail menampilkan nama storage, status, dan sisa kapasitasnya. Yang **tidak** pernah ditampilkan ke",
    "browser: Account ID, nama bucket, object key, Access Key ID lengkap, dan Secret Access Key. Informasi itu",
    "hanya dipakai server saat menandatangani request ke R2.",
    "",
    "> [!NOTE] Kenapa lokasi disembunyikan?",
    "> Menyembunyikan lokasi fisik file adalah inti dari konsep storage pool: pengguna cukup mengenal satu",
    "> domain. Ini juga memperkecil dampak bila sebuah link bocor - tidak ada informasi infrastruktur yang",
    "> terbawa.",
    "",
    "## Memindahkan file antar R2",
    "",
    "Fitur **Pindahkan** menyalin objek dari satu akun R2 ke akun lain, lalu (opsional) menghapus objek di",
    "storage asal. Gunakan untuk:",
    "",
    "- mengosongkan storage yang hampir penuh,",
    "- merapikan pool setelah menambah akun baru,",
    "- memindahkan file privat ke akun yang lebih cepat.",
    "",
    "### Cara kerja",
    "",
    "Karena S3 `CopyObject` tidak bekerja lintas akun Cloudflare, pemindahan dilakukan sebagai **job bertahap**:",
    "",
    "1. Server membuka multipart upload di bucket tujuan dan menghitung rencana part.",
    "2. Browser memanggil endpoint job berulang kali; setiap panggilan menyalin sebagian byte",
    "   (default ~48 MB per langkah) dengan pola: baca *byte range* dari sumber → tulis sebagai part di tujuan.",
    "3. Progress disimpan di server, sehingga job bisa dijeda, dilanjutkan, atau dibatalkan.",
    "4. Setelah byte terakhir, multipart diselesaikan, metadata file diperbarui ke storage tujuan, angka",
    "   pemakaian kedua storage dikoreksi, dan objek sumber dihapus (bila diminta).",
    "",
    "Hanya satu part (misalnya 8 MB) yang berada di memori pada satu waktu, dan tiap permintaan berlangsung",
    "singkat - aman untuk batas CPU/durasi serverless.",
    "",
    "### Batasan",
    "",
    "- File besar butuh beberapa menit; biarkan tab terbuka. Progress tetap tersimpan bila terputus.",
    "- Storage tujuan harus punya sisa kapasitas >= ukuran file, bila tidak job ditolak sejak awal.",
    "- Job kedaluwarsa setelah 24 jam bila tidak diselesaikan (multipart di tujuan dibatalkan otomatis saat",
    "  job dibatalkan).",
    "",
    "## Menghapus file",
    "",
    "Menghapus file melakukan tiga hal:",
    "",
    "1. Objek di bucket R2 dihapus (`DeleteObject`).",
    "2. Baris metadata di database dihapus.",
    "3. Angka pemakaian storage dikurangi.",
    "",
    "Bila penghapusan objek gagal (misalnya token kehilangan izin), aplikasi melaporkan kesalahan dan **tidak**",
    'menghapus metadata, sehingga tidak ada file "hantu" yang tercatat tetapi tidak bisa diakses. Ada opsi',
    "`keepObject` (lewat API) bila Anda sengaja hanya ingin menghapus metadata.",
    "",
    "> [!WARNING] Penghapusan bersifat permanen",
    "> R2 tidak punya trash bin. Untuk file penting, unduh salinannya lebih dulu atau aktifkan kebijakan backup",
    "> di level akun Cloudflare Anda.",
    "",
    "## Operasi massal",
    "",
    "Tabel mendukung pemilihan beberapa baris untuk: menyalin banyak link, mengubah visibilitas massal, dan",
    "menghapus massal (dengan konfirmasi). Semua operasi massal tetap melalui validasi dan rate limit yang sama",
    "seperti operasi tunggal.",
    "",
    "## Selanjutnya",
    "",
    "- [Download System](/docs/download-system) - perilaku link publik.",
    "- [Security Guide](/docs/security) - sanitasi, validasi, dan proteksi API.",
  ].join("\n"),
};
