import type { DocPage } from "@/docs/types";

/**
 * Getting Started
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "getting-started",
  title: "Getting Started",
  group: "Mulai",
  order: 10,
  icon: "rocket",
  description: "Apa itu Katsu R2 Manager, bagaimana sistem menggabungkan banyak akun Cloudflare R2 menjadi satu storage pool, dan urutan setup tanpa terminal.",
  updated: "2026-09-19",
  body: [
    "## Apa itu Katsu R2 Manager?",
    "",
    "**Katsu R2 Manager** adalah sistem *personal cloud storage* yang dibangun di atas **Cloudflare R2 Object",
    "Storage**. Ide utamanya sederhana: menggabungkan beberapa akun/bucket R2 menjadi **satu storage pool** yang",
    "terlihat seperti satu drive besar, lalu menyajikannya ke publik melalui satu domain download.",
    "",
    "Contoh nyata:",
    "",
    "| Akun | Kuota | Terpakai |",
    "| --- | --- | --- |",
    "| R2 Account 1 | 10 GB | 8 GB |",
    "| R2 Account 2 | 10 GB | 3 GB |",
    "| R2 Account 3 | 10 GB | 10 GB |",
    "| **Pool gabungan** | **30 GB** | **21 GB** |",
    "",
    "Pengunjung hanya melihat `download.domain.com` dan satu daftar file. Mereka **tidak pernah tahu** file",
    "tersimpan di akun mana, bucket apa, atau object key-nya seperti apa. Semua detail itu disembunyikan di",
    "sisi server.",
    "",
    "> [!TIP] Tanpa terminal sama sekali",
    "> Seluruh alur - membuat bucket, membuat token, mengisi environment variables, membuat tabel database,",
    "> sampai deploy - dilakukan lewat **Cloudflare Dashboard**, **Vercel Dashboard**, dan **browser**. Tidak",
    "> ada perintah `npm`, `wrangler`, `git`, dan tidak butuh VPS.",
    "",
    "## Fitur utama",
    "",
    "- **Public Download Center** (`/`) - daftar file publik, pencarian, filter kategori, halaman detail file,",
    "  dan link download yang mendukung *resume*.",
    "- **Admin Dashboard** (`/admin`) - statistik pool, status tiap R2, file terbaru, dan unduhan terpopuler.",
    "- **Multi R2 Storage Manager** (`/admin/storage`) - tambah/edit/hapus banyak akun R2, uji koneksi, dan",
    "  sinkronisasi pemakaian kapasitas.",
    "- **Auto Upload Manager** (`/admin/upload`) - drag & drop, multipart upload langsung dari browser ke R2,",
    "  progress bar, pause/resume, retry otomatis, dan pemilihan storage otomatis.",
    "- **File Manager** (`/admin/files`) - cari, rename, hapus, ubah visibilitas, salin link, lihat lokasi",
    "  storage, dan pindahkan file antar akun R2.",
    "- **Dokumentasi website** (`/docs`) - sidebar, pencarian, table of contents, responsif di mobile.",
    "",
    "## Cara kerja sistem",
    "",
    "```text",
    "Browser User",
    "      |",
    "      v",
    "Katsu R2 Manager  (Next.js di Cloudflare Pages / Vercel)",
    "      |",
    "      +-------- Public Download Center  (/)         -> daftar file + streaming download",
    "      |",
    "      +-------- Admin Panel             (/admin)    -> login, dashboard, storage, upload, files",
    "      |",
    "      v",
    "Storage Manager (lib/r2)  -> memilih R2 terbaik, menandatangani request S3 (SigV4)",
    "      |",
    "      +-- R2 Account 1  (bucket katsu-pool-01)",
    "      +-- R2 Account 2  (bucket katsu-pool-02)",
    "      +-- R2 Account 3  (bucket katsu-pool-03)",
    "      +-- R2 Account N",
    "      |",
    "      v",
    "Metadata Database (Cloudflare D1 atau KV) -> files, storages, upload_sessions",
    "```",
    "",
    "Tiga lapisan penting:",
    "",
    "1. **Lapisan publik** hanya membaca metadata yang aman untuk dipublikasikan (nama file, ukuran, tipe,",
    "   tanggal, jumlah unduhan) dan melakukan streaming byte dari R2.",
    "2. **Lapisan admin** dilindungi login + session cookie + token CSRF, dan satu-satunya tempat kredensial R2",
    "   dipakai.",
    "3. **Lapisan storage** berisi implementasi S3 Signature V4 sendiri (tanpa AWS SDK) sehingga kode yang sama",
    "   jalan di Node.js maupun workerd, termasuk multipart upload dan pre-signed URL.",
    "",
    "## Alur hidup sebuah file",
    "",
    "1. Admin memilih file di `/admin/upload` (drag & drop atau pilih dari HP/PC).",
    "2. Browser mengirim ukuran file ke `POST /api/admin/uploads/init`.",
    "3. **Auto storage selection** memeriksa semua R2: hanya storage aktif dengan sisa kapasitas cukup yang",
    "   menjadi kandidat, lalu yang **free space-nya paling besar** dipilih.",
    "4. Server membuka *multipart upload* di bucket terpilih dan mengembalikan **pre-signed URL** per bagian",
    "   (part).",
    "5. Browser mengunggah tiap part **langsung ke R2** - file tidak pernah melewati server aplikasi, jadi",
    "   tidak ada konsumsi RAM dan tidak ada batas ukuran dari sisi aplikasi.",
    "6. Setelah semua part selesai, browser memanggil `POST /api/admin/uploads/complete`.",
    "7. Server menyelesaikan multipart upload, memverifikasi ukuran lewat `HeadObject`, lalu menyimpan metadata",
    "   ke D1/KV dan menambah angka pemakaian storage.",
    "8. File langsung muncul di Download Center dengan link `/download/<id>` yang bisa dibagikan.",
    "",
    "## Yang Anda butuhkan",
    "",
    "| Kebutuhan | Keterangan |",
    "| --- | --- |",
    "| Akun Cloudflare | Boleh beberapa akun, masing-masing mendapat kuota gratis R2 (10 GB) |",
    "| Domain (opsional tapi disarankan) | Misalnya `download.domain.com` untuk Download Center |",
    "| Akun Vercel **atau** Cloudflare | Untuk hosting aplikasi Next.js ini |",
    "| Browser modern | Chrome/Edge/Firefox/Safari versi terbaru, di HP atau PC |",
    "",
    "## Urutan setup (tanpa terminal)",
    "",
    "1. **Siapkan R2** - buat bucket, catat Account ID, buat API token S3, salin Access Key ID & Secret Access",
    "   Key. Lihat [Cloudflare R2 Setup](/docs/r2-setup).",
    "2. **Siapkan database** - buat D1 (disarankan) atau KV, salin id-nya, buat API token Cloudflare.",
    "   Lihat [Database Setup](/docs/database-setup).",
    "3. **Deploy aplikasi** - lewat dashboard Cloudflare (OpenNext) atau import repo di Vercel.",
    "   Lihat [Deployment](/docs/deployment).",
    "4. **Isi environment variables** di dashboard hosting. Daftar lengkapnya ada di",
    "   [Environment Variables](/docs/environment-variables).",
    "5. **Buka `/setup`** pada domain Anda - halaman ini membuat `ADMIN_PASSWORD_HASH`, `SESSION_SECRET`, dan",
    "   `CREDENTIAL_ENCRYPTION_KEY` langsung di browser Anda (password tidak pernah dikirim ke server).",
    "6. **Buka `/admin/settings`** lalu klik **Initialize database** untuk membuat tabel otomatis.",
    "7. **Tambah storage** di `/admin/storage`, uji koneksi, lalu mulai upload di `/admin/upload`.",
    "",
    "> [!NOTE] Mode demo",
    "> Set `DEMO_MODE=true` bila Anda ingin melihat tampilan Download Center dan Admin Dashboard dengan data",
    "> contoh sebelum menyiapkan Cloudflare. Pada mode ini upload/download ke R2 dinonaktifkan.",
    "",
    "## Struktur project",
    "",
    "```text",
    "/",
    "├── app/                # Next.js App Router: halaman publik, admin, docs, API routes",
    "│   ├── (halaman)       # /, /file/[id], /docs, /docs/[slug], /admin/*, /setup",
    "│   ├── api/            # /api/auth, /api/admin/*, /api/public/*, /api/health",
    "│   └── download/[id]/  # endpoint streaming download (HTTP Range)",
    "├── components/         # UI: design system (ui/), admin, public, docs, site",
    "├── lib/                # inti aplikasi",
    "│   ├── auth/           # password PBKDF2, session HMAC, CSRF",
    "│   ├── r2/             # S3 SigV4 client, multipart, storage manager",
    "│   ├── db/             # adapter D1 / KV / memory + vault enkripsi kredensial",
    "│   ├── services/       # uploads, files, storages, downloads",
    "│   ├── security/       # rate limit, sanitasi, state store",
    "│   └── api/            # validasi (zod), guard, response envelope",
    "├── database/           # schema.sql, seed.sql, panduan inisialisasi",
    "├── workers/            # Cloudflare Worker opsional untuk download throughput tinggi",
    "├── docs/               # konten dokumentasi yang dirender di /docs",
    "├── public/             # logo, manifest, robots",
    "├── proxy.ts            # proteksi route /admin (Next.js 16: pengganti middleware)",
    "├── .env.example        # template environment variables",
    "└── README.md           # panduan deploy lewat dashboard",
    "```",
    "",
    "## Selanjutnya",
    "",
    "- [Cloudflare R2 Setup](/docs/r2-setup) - membuat bucket dan mengambil Access Key/Secret Key.",
    "- [Database Setup](/docs/database-setup) - memilih D1 atau KV dan membuat tabelnya.",
    "- [Deployment](/docs/deployment) - deploy lewat dashboard Cloudflare atau Vercel.",
    "- [Menambahkan Storage](/docs/add-storage) - memakai panel Multi R2 Storage Manager.",
  ].join("\n"),
};
