import type { DocPage } from "@/docs/types";

/**
 * Cloudflare R2 Setup
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "r2-setup",
  title: "Cloudflare R2 Setup",
  group: "Cloudflare",
  order: 20,
  icon: "cloud",
  description: "Langkah membuat bucket R2, mengambil Account ID, membuat API token S3, mendapatkan Access Key ID dan Secret Access Key, serta memasang CORS policy - semuanya dari Cloudflare Dashboard.",
  updated: "2026-09-19",
  body: [
    "Halaman ini menjelaskan cara menyiapkan **satu akun Cloudflare R2** sampai semua data yang dibutuhkan",
    "Katsu R2 Manager terkumpul. Ulangi langkah yang sama untuk setiap akun tambahan yang ingin digabungkan ke",
    "dalam storage pool.",
    "",
    "> [!NOTE] Semua lewat dashboard",
    "> Tidak ada satu pun langkah di halaman ini yang membutuhkan terminal, CLI, atau wrangler. Seluruhnya",
    "> dilakukan dengan mouse di [dash.cloudflare.com](https://dash.cloudflare.com).",
    "",
    "## Kenapa R2?",
    "",
    "Cloudflare R2 adalah object storage yang kompatibel dengan API S3 dan **tidak memungut biaya egress**",
    "(bandwidth keluar). Setiap akun Cloudflare mendapat kuota gratis bulanan:",
    "",
    "| Komponen | Kuota gratis |",
    "| --- | --- |",
    "| Penyimpanan | 10 GB-bulan |",
    "| Operasi Class A (PUT, POST, LIST, multipart) | 1.000.000 / bulan |",
    "| Operasi Class B (GET, HEAD) | 10.000.000 / bulan |",
    "| Egress (bandwidth keluar) | Gratis |",
    "",
    "Karena setiap akun mendapat 10 GB gratis, tiga akun berarti 30 GB - persis alasan kenapa proyek ini",
    "menggabungkan banyak akun menjadi satu pool.",
    "",
    "## Langkah 1 - Aktifkan R2",
    "",
    "1. Masuk ke [dash.cloudflare.com](https://dash.cloudflare.com).",
    "2. Pada sidebar kiri pilih **Storage & Databases** → **R2 Object Storage**.",
    "3. Klik **Purchase R2 Plan** (atau **Get started**). Pilih paket **Free** / *pay as you go*: selama",
    "   pemakaian berada di dalam kuota gratis, tagihannya nol.",
    "4. Selesaikan aktivasi (Cloudflare mungkin meminta metode pembayaran untuk verifikasi, meskipun kuota",
    "   gratis tidak menagih apa pun).",
    "",
    "## Langkah 2 - Buat bucket",
    "",
    "1. Masih di halaman **R2 Object Storage**, klik **Create bucket**.",
    "2. Isi:",
    "   - **Bucket name**: misalnya `katsu-pool-01`. Nama harus unik di seluruh Cloudflare, hanya huruf kecil,",
    "     angka, strip, dan titik.",
    "   - **Location**: pilih **Automatic** (atau **Jurisdiction** bila Anda butuh data tetap di wilayah",
    "     tertentu, misalnya `EU`).",
    "   - **Storage class**: **Standard**.",
    "3. Klik **Create bucket**.",
    "",
    "> [!TIP] Satu bucket per akun",
    "> Untuk pool yang rapi, buat satu bucket per akun Cloudflare dengan penomoran yang konsisten",
    "> (`katsu-pool-01`, `katsu-pool-02`, ...). Anda tetap boleh menambahkan beberapa bucket dari satu akun -",
    "> aplikasi memperlakukan setiap entri storage secara independen.",
    "",
    "## Langkah 3 - Ambil Account ID",
    "",
    "Account ID adalah identitas akun Cloudflare (32 karakter heksadesimal).",
    "",
    "1. Buka halaman **R2 Object Storage** (atau halaman **Overview** akun Anda).",
    "2. Di panel kanan temukan bagian **Account ID**.",
    "3. Klik ikon salin di sebelahnya.",
    "",
    "Nilai ini dipakai untuk membentuk endpoint S3 otomatis:",
    "",
    "```text",
    "https://<ACCOUNT_ID>.r2.cloudflarestorage.com",
    "```",
    "",
    "Aplikasi membentuk endpoint itu sendiri, jadi kolom **Endpoint** pada form storage boleh dikosongkan.",
    "",
    "## Langkah 4 - Buat API token S3 (Access Key & Secret Key)",
    "",
    "1. Di halaman **R2 Object Storage**, klik **Manage R2 API Tokens** (pojok kanan atas, atau menu",
    "   **API tokens** di dalam R2).",
    "2. Klik **Create API token**.",
    "3. Isi:",
    "   - **Token name**: misalnya `katsu-r2-manager-pool-01`.",
    "   - **Permissions**: pilih **Object Read & Write**. Izin ini cukup untuk upload, download, list, dan",
    "     delete object - tanpa izin administratif yang tidak dibutuhkan.",
    "   - **Specify bucket**: pilih **Apply to specific buckets only** lalu pilih bucket yang baru dibuat",
    "     (prinsip least privilege). Pilih *All buckets* hanya bila Anda memang menginginkannya.",
    "   - **Client IP Address Filtering**: boleh dikosongkan.",
    "   - **TTL**: **Forever** agar token tidak kedaluwarsa di tengah jalan (atau set tanggal panjang dan",
    "     catat tanggal rotasinya).",
    "4. Klik **Create API Token**.",
    "5. **Salin dan simpan** tiga nilai yang muncul:",
    "",
    "| Nilai | Dipakai sebagai |",
    "| --- | --- |",
    "| **Access Key ID** | `Access Key ID` pada form storage |",
    "| **Secret Access Key** | `Secret Access Key` pada form storage |",
    "| **Endpoint** | `https://<ACCOUNT_ID>.r2.cloudflarestorage.com` (opsional, otomatis terisi) |",
    "",
    "> [!WARNING] Secret Access Key hanya muncul sekali",
    "> Cloudflare hanya menampilkan **Secret Access Key** pada saat token dibuat. Bila tertutup atau hilang,",
    "> Anda harus membuat token baru. Simpan di password manager, bukan di chat atau screenshot.",
    "",
    "## Langkah 5 - Pasang CORS policy (wajib untuk upload dari browser)",
    "",
    "Upload besar dilakukan **langsung dari browser ke R2** memakai pre-signed URL. Agar browser diizinkan",
    "mengirim part dan membaca header `ETag` dari respons, bucket perlu CORS policy.",
    "",
    "1. Buka bucket Anda → tab **Settings**.",
    "2. Cari bagian **CORS Policy** → klik **Edit**.",
    "3. Pilih **JSON** dan tempel kebijakan berikut (ganti origin dengan domain aplikasi Anda):",
    "",
    "```json",
    "[",
    "  {",
    '    "AllowedOrigins": [',
    '      "https://download.domain.com",',
    '      "https://katsu-r2-manager.pages.dev"',
    "    ],",
    '    "AllowedMethods": ["GET", "PUT", "POST", "HEAD"],',
    '    "AllowedHeaders": ["*"],',
    '    "ExposeHeaders": ["ETag", "Content-Length", "Content-Range", "Accept-Ranges", "Last-Modified"],',
    '    "MaxAgeSeconds": 3600',
    "  }",
    "]",
    "```",
    "",
    "4. Klik **Save**.",
    "",
    "Penjelasan singkat:",
    "",
    "- `AllowedOrigins` harus **persis** sama dengan origin tempat admin panel dibuka (skema + host, tanpa",
    "  slash di akhir). Tambahkan beberapa origin bila Anda memakai domain preview dan domain produksi.",
    "- `ExposeHeaders` wajib memuat `ETag` - tanpa itu browser tidak bisa membaca ETag tiap part sehingga",
    "  multipart upload tidak dapat diselesaikan.",
    "- Selama `AllowedHeaders` bernilai `*`, Anda tidak perlu mendaftar header satu per satu.",
    "",
    "> [!TIP] Lupa memasang CORS?",
    "> Upload akan gagal dengan pesan jaringan (status 0) atau `TypeError: Failed to fetch` di console browser.",
    "> Panel upload menampilkan petunjuk otomatis bila mendeteksi kegagalan semacam ini.",
    "",
    "## Langkah 6 - Ulangi untuk akun R2 lain",
    "",
    "Untuk menambah kapasitas pool, ulangi langkah 1-5 pada akun Cloudflare lain, lalu daftarkan setiap akun di",
    "**Admin → Storage**. Kumpulan data yang dibutuhkan aplikasi untuk tiap storage:",
    "",
    "| Field di aplikasi | Sumber di Cloudflare |",
    "| --- | --- |",
    "| Storage Name | Bebas, misal `R2 Server 1` |",
    "| Account ID | Langkah 3 |",
    "| Bucket Name | Langkah 2 |",
    "| Access Key ID | Langkah 4 |",
    "| Secret Access Key | Langkah 4 |",
    "| Storage Limit | Kuota yang Anda tetapkan, misal `10 GB` |",
    "| Endpoint | Kosongkan (otomatis) |",
    "| Region | `auto` |",
    "",
    "## Verifikasi cepat",
    "",
    "Setelah storage ditambahkan lewat panel admin, gunakan tombol **Test koneksi**. Sistem menjalankan empat",
    "pemeriksaan bertingkat:",
    "",
    "1. `HeadBucket` - bucket ada dan dapat diakses.",
    "2. `ListObjectsV2` - token punya izin baca.",
    "3. `PutObject` - token punya izin tulis (objek uji `.katsu/connection-probe.txt`).",
    "4. `DeleteObject` - objek uji dibersihkan.",
    "",
    "Bila salah satu langkah gagal, hasilnya menjelaskan penyebab yang paling mungkin (Access Key salah, Secret",
    "Key salah, bucket tidak ditemukan, atau izin token kurang). Lihat",
    "[Troubleshooting](/docs/troubleshooting).",
    "",
    "## Selanjutnya",
    "",
    "- [Database Setup](/docs/database-setup) - menyiapkan D1 atau KV untuk metadata file.",
    "- [Menambahkan Storage](/docs/add-storage) - memakai panel Multi R2 Storage Manager.",
    "- [Security Guide](/docs/security) - bagaimana kredensial ini disimpan dan dilindungi.",
  ].join("\n"),
};
