import type { DocPage } from "@/docs/types";

/**
 * Security Guide
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "security",
  title: "Security Guide",
  group: "Referensi",
  order: 100,
  icon: "shield",
  description: "Model keamanan Katsu R2 Manager - autentikasi admin, hash password PBKDF2, session HMAC, CSRF, rate limiting, enkripsi kredensial R2, sanitasi filename, CSP, dan praktik operasional.",
  updated: "2026-09-19",
  body: [
    "Keamanan adalah bagian desain, bukan tambahan. Halaman ini menjelaskan apa yang sudah dibangun ke dalam",
    "aplikasi dan apa yang perlu Anda jaga sebagai operator.",
    "",
    "## Model ancaman singkat",
    "",
    "| Aset | Ancaman | Mitigasi di aplikasi |",
    "| --- | --- | --- |",
    "| Kredensial R2 | Bocor lewat frontend atau dump database | Enkripsi AES-256-GCM at rest, tidak pernah dikirim ke browser, masking di API |",
    "| Sesi admin | Pembajakan cookie, CSRF | Cookie HttpOnly + SameSite=Strict + Secure, token HMAC bertanggal kedaluwarsa, CSRF double-submit |",
    "| Password admin | Brute force, rainbow table | PBKDF2-SHA256 + salt acak 16 byte, perbandingan constant-time, rate limit per IP+username |",
    "| Metadata file | Enumerasi link publik | `downloadId` acak 10 karakter (bukan angka urut), rate limit endpoint publik |",
    "| Input pengguna | Path traversal, XSS, SQL injection | Sanitasi filename, escaping React, parameter binding di D1, validasi Zod |",
    "| Infrastruktur | Header bocor, clickjacking, MIME sniffing | CSP, X-Frame-Options DENY, nosniff, HSTS, Referrer-Policy, Permissions-Policy |",
    "",
    "## Autentikasi admin",
    "",
    "- Username & password dibaca dari `ADMIN_USERNAME` dan `ADMIN_PASSWORD_HASH`. Tidak ada tabel pengguna -",
    "  satu operator, satu kredensial, permukaan serangan minimal.",
    "- Hash memakai **PBKDF2-SHA256** dengan 16 byte salt acak dan iterasi yang tersimpan di dalam hash",
    "  (`pbkdf2-sha256$100000$salt$hash`). Verifikasi memakai perbandingan **constant-time**.",
    "- Percobaan login dibatasi `RATE_LIMIT_LOGIN_ATTEMPTS` per `RATE_LIMIT_LOGIN_WINDOW_SECONDS` untuk",
    "  kombinasi IP+username. Setelah login berhasil, penghitung dibersihkan.",
    '- Login gagal selalu mengembalikan pesan yang sama ("Username atau password salah") agar tidak membocorkan',
    "  apakah username-nya benar.",
    "",
    "> [!NOTE] PBKDF2 di browser",
    "> Hash dibuat oleh **Setup Assistant** (`/setup`) memakai Web Crypto di browser Anda. Password **tidak",
    "> pernah dikirim ke server**; yang Anda salin ke environment variable hanyalah hash-nya. Karena itu halaman",
    "> ini aman dibuka sebelum sistem terkonfigurasi.",
    "",
    "### Memilih jumlah iterasi",
    "",
    "| Platform | Rekomendasi |",
    "| --- | --- |",
    "| Vercel / Node.js | 100.000 - 210.000 |",
    "| Cloudflare Workers Paid | 100.000 (`limits.cpu_ms` sudah diset 30000) |",
    "| Cloudflare Workers Free (10 ms CPU) | 10.000 - 25.000 |",
    "",
    "Login hanya terjadi sekali per sesi dan dilindungi rate limit, jadi menurunkan iterasi di platform dengan",
    "batas CPU ketat adalah kompromi yang wajar.",
    "",
    "## Session",
    "",
    "- Token berbentuk `v1.<payload>.<signature>`; payload berisi `sub`, `iat`, `exp`, `jti`.",
    "- Ditandatangani **HMAC-SHA256** dengan `SESSION_SECRET` dan diverifikasi dengan perbandingan constant-time.",
    "- Cookie: `HttpOnly`, `Secure` (otomatis aktif di HTTPS), `SameSite=Strict`, `Path=/`, umur",
    "  `SESSION_TTL_HOURS`.",
    "- Ada *clock skew* 60 detik untuk menghindari penolakan akibat selisih jam server.",
    "- `proxy.ts` (pengganti middleware di Next.js 16) menolak akses `/admin/*` tanpa sesi valid **dan** setiap",
    "  API route admin memverifikasi ulang sesi - jadi proteksi tetap berlaku walaupun proxy dilewati.",
    "",
    "Logout menghapus cookie sesi dan cookie CSRF dengan `Max-Age=0`.",
    "",
    "## CSRF",
    "",
    "Semua request yang mengubah keadaan (`POST`, `PATCH`, `DELETE`) ke `/api/admin/*` wajib menyertakan header",
    "`x-katsu-csrf` yang isinya sama dengan cookie `katsu_csrf` (pola *double submit*). Cookie ini",
    "`SameSite=Strict` dan dapat dibaca JavaScript aplikasi sendiri saja. Request yang tidak cocok ditolak",
    "`403 csrf_failed`.",
    "",
    "Klien resmi membaca cookie itu lewat helper `apiFetch()` sehingga Anda tidak perlu mengurusnya manual.",
    "",
    "## Rate limiting",
    "",
    "| Scope | Default | Penyimpanan |",
    "| --- | --- | --- |",
    "| Login | 6 percobaan / 15 menit | Database (`app_state`) - berlaku lintas instance |",
    "| API admin | 240 request / menit | Database |",
    "| API publik | 240 request / menit | Database |",
    "| Download | 120 request / menit / IP | Memori per isolate (hemat, karena satu file bisa memicu banyak range request) |",
    "",
    "Bila database tidak dapat diakses, rate limiter **fail-open** dan mencatat peringatan di log - aplikasi",
    "tetap可用 tersedia, degradasi terlihat di log. (Semua nilai dapat diubah lewat env.)",
    "",
    "## Proteksi kredensial R2",
    "",
    "1. **Enkripsi at rest**: Secret Access Key dienkripsi AES-256-GCM dengan kunci dari",
    "   `CREDENTIAL_ENCRYPTION_KEY`, disimpan sebagai `enc:v1:<iv>.<ciphertext>`.",
    "2. **Tidak pernah ke browser**: seluruh respons API memakai proyeksi aman (`toSafeStorage`) yang membuang",
    "   field kredensial. Access Key ID hanya muncul sebagai `8f2a****c31d`.",
    "3. **Dekripsi seketika**: kredensial hanya didekripsi di memori server tepat sebelum menandatangani request",
    "   S3, dan client R2 di-cache per versi record (rotasi kredensial otomatis membatalkan cache).",
    "4. **Pre-signed URL berumur pendek**: URL upload part berlaku 6 jam; URL download mode `redirect` dibatasi",
    "   15 menit.",
    "5. **Least privilege**: dokumentasi menyarankan token R2 dengan izin *Object Read & Write* pada bucket",
    "   tertentu saja, dan token API Cloudflare dengan izin D1/KV saja.",
    "",
    "## Validasi & sanitasi input",
    "",
    "- Semua body request divalidasi **Zod** sebelum menyentuh logika (skema di `lib/api/schemas.ts`): tipe,",
    "  panjang, rentang angka, format Account ID (32 hex), format nama bucket, dan enum.",
    "- Query string juga divalidasi, dengan batas panjang untuk mencegah payload pencarian raksasa.",
    "- **Filename** disanitasi: normalisasi NFKC, penghapusan karakter kontrol & zero-width, penggantian `/ \\ : *",
    '  ? " < > |`, penolakan nama reserved Windows, pembatasan 180 karakter, dan fallback `file`.',
    "- **Object key** dibangun server-side dari prefiks + tahun/bulan + id unik + nama aman - pengguna tidak",
    "  pernah menentukan key sendiri, sehingga path traversal tidak mungkin.",
    "- Query D1 selalu memakai **parameter binding** (`?1`, `?2`, ...); tidak ada string concatenation SQL.",
    "- Istilah pencarian di-escape untuk `LIKE` (`\\`, `%`, `_`).",
    "",
    "## Header keamanan",
    "",
    "Dikirim untuk seluruh rute (kecuali penyesuaian kecil pada endpoint download):",
    "",
    "```text",
    "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline';",
    "  style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:;",
    "  connect-src 'self' blob: data: https://*.r2.cloudflarestorage.com https://*.r2.dev https://api.cloudflare.com;",
    "  frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self';",
    "  upgrade-insecure-requests",
    "X-Content-Type-Options: nosniff",
    "X-Frame-Options: DENY",
    "Referrer-Policy: strict-origin-when-cross-origin",
    "Permissions-Policy: camera=(), microphone=(), geolocation=(), browsing-topics=()",
    "Cross-Origin-Opener-Policy: same-origin",
    "Cross-Origin-Resource-Policy: same-origin   (cross-origin untuk /download/*)",
    "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload",
    "```",
    "",
    "`connect-src` menyertakan `*.r2.cloudflarestorage.com` karena multipart upload berjalan langsung dari",
    "browser ke R2 - tanpa izin ini upload akan diblokir CSP.",
    "",
    "Endpoint download memakai `Cross-Origin-Resource-Policy: cross-origin` agar file bisa diunduh/diputar dari",
    "aplikasi lain milik Anda bila diperlukan.",
    "",
    "## Logging",
    "",
    "Log berbentuk JSON dengan field `level`, `scope`, `message`, `at`, dan `meta`. Logger **menyensor** field",
    "bernama `secret`, `password`, `token`, `authorization`, `cookie`, `accessKeyId`, `secretAccessKey`, dan",
    "`x-amz-signature` menjadi `[redacted]`. Gunakan `LOG_LEVEL=debug` saat menelusuri masalah, lalu kembalikan",
    "ke `info`.",
    "",
    "## Praktik operasional yang disarankan",
    "",
    "1. **Rotasi rahasia secara berkala**: `SESSION_SECRET`, `CREDENTIAL_ENCRYPTION_KEY`, token R2, dan token",
    "   API Cloudflare. Setelah mengganti `CREDENTIAL_ENCRYPTION_KEY`, simpan ulang setiap storage agar",
    "   kredensialnya dienkripsi ulang dengan kunci baru.",
    "2. **Pisahkan akun**: gunakan akun Cloudflare berbeda untuk R2 dan untuk D1 bila memungkinkan, agar kebocoran",
    "   satu token tidak membuka semuanya.",
    "3. **Backup metadata**: ekspor D1 (dashboard → D1 → Export) secara berkala. Objek di R2 adalah sumber",
    "   kebenaran untuk data, metadata adalah peta-nya.",
    "4. **Batasi admin**: `ADMIN_USERNAME` sebaiknya bukan `admin`, dan password minimal 16 karakter acak.",
    "5. **Pantau log**: Cloudflare → Workers → Logs; Vercel → Observability. Cari `warn`/`error` dari scope",
    "   `auth-login`, `r2-client`, `storage-manager`.",
    "6. **Uji setelah perubahan**: `Test koneksi` untuk tiap storage, `/api/health`, dan satu upload+download",
    "   kecil setelah deploy.",
    "7. **Jangan aktifkan `DEMO_MODE` di produksi** - mode ini memakai data contoh dan menonaktifkan transfer R2.",
    "",
    "## Yang bukan tanggung jawab aplikasi",
    "",
    "- **Enkripsi isi file**: R2 mengenkripsi data at rest di sisi Cloudflare, tetapi aplikasi tidak melakukan",
    "  enkripsi end-to-end pada isi file. Bila Anda menyimpan data sangat sensitif, enkripsi file sebelum upload",
    "  (misalnya dengan 7-Zip/zip berpassword di perangkat Anda).",
    "- **Autentikasi multi pengguna**: sistem dirancang untuk satu operator. Menambah banyak pengguna berarti",
    "  menambah tabel pengguna, peran, dan audit log.",
    "- **Moderasi konten**: Anda bertanggung jawab atas file yang dibagikan melalui domain Anda.",
    "",
    "## Selanjutnya",
    "",
    "- [Troubleshooting](/docs/troubleshooting) - menangani insiden.",
    "- [Environment Variables](/docs/environment-variables) - knob keamanan yang bisa disetel.",
  ].join("\n"),
};
