import type { DocPage } from "@/docs/types";

/**
 * Troubleshooting
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "troubleshooting",
  title: "Troubleshooting",
  group: "Referensi",
  order: 110,
  icon: "wrench",
  description: "Tabel gejala, penyebab, dan solusi untuk masalah yang paling sering muncul - login, database, storage R2, CORS, upload multipart, download, dan deploy.",
  updated: "2026-09-19",
  body: [
    "Halaman ini disusun berdasarkan gejala yang Anda lihat, bukan berdasarkan komponen, supaya cepat ditelusuri.",
    "",
    "## Langkah pertama: baca diagnostics",
    "",
    "1. Buka **`/api/health`** - menampilkan status konfigurasi, driver database, dan jumlah masalah pemblokir.",
    "2. Login ke **`/admin/settings`** → bagian **Diagnostics** - daftar semua environment variable yang hilang",
    "   beserta cara memperbaikinya.",
    "3. Lihat log platform:",
    "   - **Cloudflare**: Workers & Pages → aplikasi Anda → **Logs** (aktifkan *Live* atau *Workers Logs*).",
    "   - **Vercel**: Project → **Observability** / **Logs**, pilih deployment yang aktif.",
    "",
    "## Tabel cepat",
    "",
    "| Gejala | Penyebab paling mungkin | Solusi |",
    "| --- | --- | --- |",
    '| Login selalu "Username atau password salah" | `ADMIN_PASSWORD_HASH` belum diisi atau password salah | Buat ulang hash di `/setup`, salin persis (tanpa spasi/baris baru), redeploy |',
    "| Login berhasil lalu terlempar lagi | `SESSION_SECRET` kosong/berubah, atau cookie diblokir | Set `SESSION_SECRET` stabil, pastikan akses lewat HTTPS, periksa cookie `katsu_session` |",
    "| Halaman `/admin` terus redirect ke login | Sesi kedaluwarsa atau `SESSION_TTL_HOURS` terlalu kecil | Login ulang; naikkan TTL bila perlu |",
    "| `403 csrf_failed` saat menyimpan | Header `x-katsu-csrf` tidak terkirim / cookie CSRF terhapus | Reload halaman (klien resmi membaca cookie otomatis), pastikan cookie tidak diblokir browser |",
    "| `429 too_many_attempts` | Rate limit login | Tunggu sesuai `Retry-After` (default 15 menit) |",
    "| `503 admin_not_configured` | `ADMIN_PASSWORD_HASH` atau `SESSION_SECRET` kosong | Isi keduanya lalu redeploy |",
    "| `503 database_not_configured` | `DATABASE_ID`/`CLOUDFLARE_API_TOKEN`/`CLOUDFLARE_ACCOUNT_ID` kosong | Lengkapi env, pastikan token punya izin **D1: Edit** |",
    "| `502` dengan pesan D1 | Token salah izin, database id salah, atau tabel belum dibuat | Periksa token di dashboard → API Tokens; jalankan **Initialize database** |",
    "| Dashboard kosong padahal sudah upload | Driver database berpindah ke `memory` | Lihat catatan driver di Diagnostics; isi identifier database yang benar |",
    "| `503 encryption_key_missing` saat menambah storage | `CREDENTIAL_ENCRYPTION_KEY` kosong | Generate di `/setup`, simpan sebagai Secret, redeploy |",
    "| Test koneksi: `AccessDenied` | Token R2 tidak mencakup bucket, atau Access Key salah | Buat ulang token R2 dengan izin *Object Read & Write* pada bucket tsb |",
    "| Test koneksi: `SignatureDoesNotMatch` | Secret Access Key salah/kedaluwarsa | Buat token baru, salin Secret Access Key yang baru |",
    "| Test koneksi: `NoSuchBucket` | Nama bucket atau Account ID keliru | Samakan dengan yang tampil di dashboard R2 |",
    "| Test koneksi: tulis objek uji gagal | Izin tulis kurang | Ubah permission token menjadi *Object Read & Write* |",
    "| `507 no_storage_available` | Tidak ada storage dengan sisa kapasitas cukup | Tambah storage, hapus file, naikkan limit, atau jalankan **Sync** |",
    '| Upload gagal tanpa status (0) / "Failed to fetch" | CORS bucket belum diset | Pasang CORS policy + `ExposeHeaders: ["ETag"]` (lihat R2 Setup) |',
    "| Upload berhenti di 99% | `CompleteMultipartUpload` ditolak karena ETag part tidak terbaca | Pastikan `ETag` ada di `ExposeHeaders` CORS |",
    "| Upload lambat padahal koneksi cepat | Part terlalu kecil / paralel terlalu rendah | Naikkan ukuran part (mis. 32 MB) dan paralel part (3-6) di pengaturan upload |",
    '| "Sesi upload tidak ditemukan" saat resume | Sesi dibersihkan (>7 hari) atau database berganti | Mulai upload ulang; file lama di R2 bisa dibersihkan dari dashboard |',
    "| Resume tidak melanjutkan part | File dipilih ulang dengan versi berbeda | Pastikan memilih file yang sama persis (nama+ukuran+lastModified) |",
    "| Download `404 file_not_found` | `downloadId` salah atau file dihapus/perubahan visibilitas ke privat | Salin ulang link dari File Manager |",
    "| Download `503 storage_missing` | Storage tempat file berada dihapus dari pool | Tambahkan kembali storage dengan id/bucket yang sama, atau pindahkan file |",
    "| Download putus-putus / tidak bisa resume | Mode `redirect` + klien tidak mengikuti Range | Gunakan `DOWNLOAD_MODE=stream` atau `worker` |",
    "| Download sangat lambat di Vercel | Fungsi serverless men-stream file besar | Deploy download worker (`DOWNLOAD_MODE=worker`) atau pindah hosting ke Cloudflare |",
    "| `429` saat mengunduh | Rate limit download | Naikkan `RATE_LIMIT_DOWNLOAD_REQUESTS` |",
    "| Nama file unduhan berantakan | Browser lama tanpa dukungan RFC 5987 | Normal; nama aman ASCII tetap dipakai |",
    "| Deploy Cloudflare gagal: `entry-point .open-next/worker.js not found` | Build command bukan OpenNext | Set build command `npx opennextjs-cloudflare build` |",
    "| Deploy Cloudflare gagal: `name` tidak cocok | `wrangler.jsonc` `name` ≠ nama Worker | Samakan keduanya (termasuk `services[0].service`) |",
    "| Worker error 1102 (exceeded CPU) saat login | Iterasi PBKDF2 terlalu tinggi untuk paket free | Buat hash dengan iterasi lebih rendah, atau upgrade ke Workers Paid |",
    "| Halaman error 500 acak | Secret kurang / database tidak terjangkau | Periksa log; jalankan Diagnostics |",
    "| Data hilang setelah restart | `DATABASE_DRIVER=memory` atau `DEMO_MODE=true` | Pindahkan ke D1/KV dan matikan demo mode |",
    "",
    "## Resep perbaikan terarah",
    "",
    "### A. Aplikasi tidak bisa membaca environment variable",
    "",
    "1. Pastikan variabel di-set pada **environment yang benar** (Production vs Preview vs Development di Vercel).",
    "2. Di Cloudflare, variabel baru aktif setelah menekan **Deploy**.",
    "3. Periksa salah tempel: nilai tidak boleh mengandung kutip, spasi di awal/akhir, atau baris baru.",
    "4. Buka `/api/health` dan bandingkan `database.driver` serta `downloadMode` dengan yang Anda harapkan.",
    "",
    "### B. D1: tabel sudah ada tetapi aplikasi bilang belum",
    "",
    "Jalankan **Admin → Settings → Initialize database**. Semua statement memakai `CREATE TABLE IF NOT EXISTS`,",
    "sehingga aman dijalankan berulang kali.",
    "",
    "### C. CORS R2",
    "",
    "Buka bucket → **Settings** → **CORS Policy** → tempel:",
    "",
    "```json",
    "[",
    "  {",
    '    "AllowedOrigins": ["https://download.domain.com"],',
    '    "AllowedMethods": ["GET", "PUT", "POST", "HEAD"],',
    '    "AllowedHeaders": ["*"],',
    '    "ExposeHeaders": ["ETag", "Content-Length", "Content-Range", "Accept-Ranges", "Last-Modified"],',
    '    "MaxAgeSeconds": 3600',
    "  }",
    "]",
    "```",
    "",
    "Setelah menyimpan, uji ulang upload. Bila origin Anda memakai port (misalnya preview lokal), sertakan",
    "bentuk lengkapnya termasuk port.",
    "",
    "### D. Membersihkan sisa multipart upload",
    "",
    "Upload yang dibatalkan di tengah jalan dapat meninggalkan part yang tetap dihitung sebagai pemakaian.",
    "Bersihkan dari dashboard Cloudflare:",
    "",
    "1. R2 → bucket Anda → **Settings** → **Object lifecycle rules** → buat aturan **Abort incomplete multipart",
    "   uploads** setelah 7 hari.",
    "2. Atau jalankan **Sync** pada kartu storage setelah membersihkan manual agar angka pemakaian akurat.",
    "",
    "### E. Memulihkan akses admin",
    "",
    "Bila password hilang:",
    "",
    "1. Buka `/setup` (halaman ini tidak memerlukan login).",
    "2. Buat hash baru dari password baru Anda.",
    "3. Perbarui `ADMIN_PASSWORD_HASH` di dashboard hosting → redeploy.",
    "",
    "Semua sesi lama tetap valid sampai kedaluwarsa; untuk memutus semuanya segera, ganti juga `SESSION_SECRET`.",
    "",
    "### F. Mengganti `CREDENTIAL_ENCRYPTION_KEY`",
    "",
    "Kunci lama dibutuhkan untuk mendekripsi kredensial yang sudah tersimpan:",
    "",
    "1. Pastikan aplikasi masih bisa memakai kunci lama (jangan langsung menghapusnya).",
    "2. Buka **Admin → Storage**, edit tiap storage, isi **Secret Access Key** dengan nilai yang sama, simpan.",
    "   Nilai akan dienkripsi ulang dengan kunci baru.",
    "3. Setelah semua storage disimpan ulang, ganti `CREDENTIAL_ENCRYPTION_KEY` di dashboard → redeploy.",
    "4. Jalankan **Test koneksi** pada setiap storage untuk memastikan.",
    "",
    "## Masih buntu?",
    "",
    "Kumpulkan informasi berikut sebelum mencari bantuan:",
    "",
    "- keluaran `/api/health`,",
    "- daftar masalah dari **Admin → Settings → Diagnostics**,",
    "- potongan log platform (tanpa secret) saat error terjadi,",
    "- mode download, driver database, dan platform hosting yang dipakai.",
    "",
    "Lalu buka issue di repository dengan informasi tersebut.",
  ].join("\n"),
};
