import type { DocPage } from "@/docs/types";

/**
 * Upload Guide
 *
 * Konten ditulis sebagai markdown di dalam array baris supaya tetap mudah dibaca
 * dan bisa dirender di runtime mana pun (Node.js, workerd, browser) tanpa loader.
 */
export const page: DocPage = {
  slug: "upload-guide",
  title: "Upload Guide",
  group: "Panduan Admin",
  order: 70,
  icon: "upload",
  description: "Cara memakai Auto Upload Manager - drag and drop, upload dari HP atau PC, multipart upload 5 GB+, progress bar, pause/resume, retry otomatis, dan resume setelah halaman ditutup.",
  updated: "2026-09-19",
  body: [
    "**Auto Upload Manager** (`/admin/upload`) mengunggah file dari browser **langsung ke Cloudflare R2**",
    "memakai pre-signed URL multipart. File tidak pernah melewati server aplikasi, sehingga:",
    "",
    "- tidak ada file yang ditampung di RAM server,",
    "- ukuran file praktis tidak dibatasi oleh platform hosting,",
    "- koneksi lambat atau terputus bisa dilanjutkan (resume),",
    "- biaya operasi Class A tetap terhitung normal di R2.",
    "",
    "## Cara pakai (cepat)",
    "",
    "1. Buka `/admin/upload`.",
    "2. Seret file ke area drop, atau klik untuk memilih dari HP/PC. Boleh banyak file sekaligus, dan boleh",
    "   satu folder penuh (tombol **Upload folder**).",
    "3. Perhatikan kartu tiap file: nama, ukuran, storage tujuan hasil pemilihan otomatis, progress, kecepatan,",
    "   dan sisa waktu.",
    "4. Tunggu sampai status **Selesai**, lalu salin link download-nya.",
    "",
    "Kontrol per file: **Pause**, **Lanjutkan**, **Ulangi**, **Batalkan**. Kontrol global: **Jeda semua**,",
    "**Lanjutkan semua**, **Bersihkan yang selesai**, serta pengaturan jumlah file paralel dan ukuran part.",
    "",
    "## Yang terjadi di balik layar",
    "",
    "```text",
    "Browser                     Aplikasi (Next.js)              Cloudflare R2",
    "  |                                |                            |",
    "  |-- POST /api/admin/uploads/init |                            |",
    "  |                                |-- pilih storage (auto)     |",
    "  |                                |-- CreateMultipartUpload -->|",
    "  |<-- sessionId + pre-signed URL tiap part                     |",
    "  |                                                             |",
    "  |-- PUT part 1 (8 MB) --------------------------------------->|",
    "  |-- PUT part 2 (8 MB) --------------------------------------->|",
    "  |-- PUT part N ------------------------------------------------>|",
    "  |                                                             |",
    "  |-- POST /api/admin/uploads/complete                          |",
    "  |                                |-- CompleteMultipartUpload->|",
    "  |                                |-- HeadObject (verifikasi)  |",
    "  |                                |-- simpan metadata ke D1/KV |",
    "  |<-- file + link /download/<id>                               |",
    "```",
    "",
    "## Ukuran part dan batas teknis",
    "",
    "| Parameter | Nilai |",
    "| --- | --- |",
    "| Ukuran part default | `DEFAULT_PART_SIZE_MB` = 8 MB |",
    "| Ukuran part minimum | 5 MB (aturan S3/R2 untuk part selain yang terakhir) |",
    "| Jumlah part maksimum | 10.000 (aturan S3/R2) |",
    "| Ukuran file maksimum | `MAX_UPLOAD_SIZE_GB` = 20 GB (bisa dinaikkan; R2 mendukung 5 TiB per object) |",
    "| Part paralel per file | `MAX_CONCURRENT_PARTS` = 3 (dapat diubah di UI, 1-8) |",
    "| File paralel | dapat diubah di UI (1-6) |",
    "",
    "Bila ukuran file dibagi ukuran part menghasilkan lebih dari 10.000 part, aplikasi **memperbesar ukuran part",
    "secara otomatis** supaya upload tetap mungkin. Contoh: file 200 GB dengan part 32 MB.",
    "",
    "## Resume upload",
    "",
    "Ada dua lapis resume:",
    "",
    "1. **Dalam satu sesi browser** - bila sebuah part gagal (jaringan putus, timeout), part itu diulang dengan",
    "   *exponential backoff* + jitter sampai beberapa kali sebelum ditandai gagal. File lain di antrean tetap",
    "   jalan.",
    "2. **Setelah halaman ditutup / reload** - antrean disimpan di **IndexedDB** browser (termasuk objek file-nya",
    "   bila browser mengizinkan), dan sesi multipart tersimpan di server (`upload_sessions`). Saat Anda kembali",
    "   ke `/admin/upload`:",
    "   - aplikasi memuat daftar sesi yang bisa dilanjutkan dari server,",
    "   - memanggil `ListParts` ke R2 untuk mengetahui part mana yang **benar-benar** sudah tersimpan,",
    "   - mencocokkannya dengan file di antrean lokal berdasarkan sidik jari `nama:ukuran:lastModified`,",
    "   - lalu melanjutkan dari part berikutnya - part yang sudah terupload tidak dikirim ulang.",
    "",
    "> [!TIP] Bila browser tidak menyimpan file-nya",
    "> Beberapa browser (terutama di iOS) tidak mengizinkan penyimpanan objek file di IndexedDB. Dalam kasus itu",
    "> sesi tetap terdaftar di server; Anda hanya perlu memilih ulang file yang sama dan menekan **Lanjutkan** -",
    "> part yang sudah terupload tetap dipakai.",
    "",
    "## Memilih storage secara manual",
    "",
    "Secara default storage dipilih otomatis (kapasitas cukup + free space terbesar). Bila ingin menentukan",
    "sendiri:",
    "",
    "1. Buka **Pengaturan upload** di panel.",
    "2. Pilih **Storage tujuan** → storage tertentu.",
    "3. Upload berikutnya memakai storage itu selama kapasitasnya cukup; bila tidak cukup, alasan penolakan",
    "   ditampilkan dan Anda bisa membiarkan sistem memilih otomatis.",
    "",
    "## Visibilitas file",
    "",
    "Saat upload, Anda bisa menentukan **Publik** (muncul di Download Center) atau **Privat** (tidak muncul di",
    "daftar publik, hanya bisa diunduh oleh admin yang sedang login). Visibilitas bisa diubah kapan saja dari",
    "File Manager.",
    "",
    "## Upload dari HP",
    "",
    "Halaman upload dirancang *mobile first*:",
    "",
    "- Tombol **Pilih file** memakai pemilih file bawaan (kamera, galeri, Files, Drive).",
    "- Tombol **Ambil foto/video** membuka kamera langsung bila perangkat mendukung.",
    "- Progress, kecepatan, dan sisa waktu tetap tampil di layar sempit.",
    "- Layar boleh dimatikan? Tidak - browser mobile umumnya menunda transfer saat tab tidak aktif. Biarkan tab",
    "  terbuka; bila terputus, gunakan **Lanjutkan**.",
    "",
    "## Batasan dan pesan error yang mungkin muncul",
    "",
    "| Pesan | Penyebab | Solusi |",
    "| --- | --- | --- |",
    "| `no_storage_available` | Tidak ada storage dengan sisa kapasitas cukup | Tambah storage, hapus file lama, atau naikkan limit |",
    "| `file_too_large` | Melebihi `MAX_UPLOAD_SIZE_GB` | Naikkan nilai variabel tersebut, lalu redeploy |",
    "| `encryption_key_missing` | `CREDENTIAL_ENCRYPTION_KEY` belum diisi | Isi lewat Setup Assistant lalu redeploy |",
    "| Gagal tanpa status (0) saat PUT part | CORS bucket belum dikonfigurasi | Pasang CORS policy, pastikan `ExposeHeaders` memuat `ETag` |",
    "| `AccessDenied` / `SignatureDoesNotMatch` | Kredensial R2 salah | Perbarui kredensial di Admin → Storage lalu **Test koneksi** |",
    "| `PreconditionFailed` / `InvalidPart` | Part tidak lengkap atau ETag berubah | Tekan **Ulangi**; sistem membaca ulang daftar part dari R2 |",
    "| Antrean kosong setelah reload | Browser membersihkan IndexedDB | Pilih ulang file; sesi server tetap ada di daftar *Bisa dilanjutkan* |",
    "",
    "## Setelah upload selesai",
    "",
    "- Link download siap dibagikan: `/download/<downloadId>`.",
    "- File langsung muncul di Download Center (`/`) bila visibilitasnya **Publik**.",
    "- Pemakaian storage bertambah otomatis; angka ini yang dipakai pemilihan storage berikutnya.",
    "",
    "## Selanjutnya",
    "",
    "- [File Management](/docs/file-management) - rename, hapus, pindah antar R2.",
    "- [Download System](/docs/download-system) - cara kerja link dan resume download.",
  ].join("\n"),
};
